### ISSUE TITLE
Display image properties for texture files. (KFileMetaData, IPropertyStore)

### ISSUE THREAD

**Issue by GerbilSoft** [GerbilSoft/rom-properties#112]
For textures, e.g. DDS, PVR, etc., the texture size should be listed on the properties page. This might be Windows-only initially, since I'm not sure if Dolphin, Nautilus, or Thunar have special handling for image properties.

**Comment by GerbilSoft** [comment]
IPropertyStore on Windows: https://msdn.microsoft.com/en-us/library/windows/desktop/cc144131(v=vs.85).aspx

**Comment by DankRank** [comment]
This may also be useful for audio (title/author/etc)

**Comment by GerbilSoft** [comment]
In progress; see https://github.com/GerbilSoft/rom-properties/tree/feature/KFileMetaData .

**Comment by GerbilSoft** [comment]
Not quite done yet. Need to implement support on at least GNOME, and maybe KDE4.

**Comment by GerbilSoft** [comment]
KDE4 is basically dead, so forget it.

Not sure what needs to be done for GNOME, so I'll postpone that for now.
