### ISSUE TITLE
Suggestion: Add support for the "internal" NES footer

### ISSUE THREAD

**Issue by mariomadproductions** [GerbilSoft/rom-properties#116]
Its internal, i.e. not part of an unofficial format like iNES.
Some links to scattered info:
https://tcrf.net/The_Blue_Marlin#Footer
http://forums.nesdev.com/viewtopic.php?t=6078&start=15
http://forums.no-intro.org/viewtopic.php?f=2&t=445
http://nintendoage.com/forum/messageview.cfm?catid=7&threadid=176401

**Comment by GerbilSoft** [comment]
Implemented in commit b3c40e51c08b59f5a77a016b37c6b5ccea30502a.
