### ISSUE TITLE
Suggestion: Add support for WUX compression format Wii U disc images

### ISSUE THREAD

**Issue by mariomadproductions** [GerbilSoft/rom-properties#117]
There are two open source tools to convert to and from WUX and extract stuff from it (latter tool only):
https://gbatemp.net/threads/wii-u-image-wud-compression-tool.397901/ (made by author of format)
https://github.com/Maschell/JWUDTool
Both authors are active online, so you can probably get format documentation from them if they have it.

**Comment by GerbilSoft** [comment]
Fixed by commit 546ae8dc5c191438e40d9a0d34d56c5ed597853c.
