### ISSUE TITLE
Add support for Wii WAD files

### ISSUE THREAD

**Issue by cheatfreak47** [GerbilSoft/rom-properties#118]
It's as the title would suggest.

Some stuff such as

- Title (Multi-Language if needed/applicable)
- Title ID (full 16 digit title ID)
- Game ID (last 8 digits of the TID converted to a string)
- Start-up IOS

would be useful information to have in there in addition to whatever else you feel like having in there

**Comment by GerbilSoft** [comment]
It seems Wii channels don't have standard icons, unlike save files; the only icons they have are the "small" animation as seen on the System Menu. We can use GameTDB downloads, though.

Both WAD files and encrypted save files use a similar format, so I can probably add save files as well. Save files **do** have GCN-style icons and banners, though at a higher resolution. (Icons are 48x48; banners are 192x64.)
