### ISSUE TITLE
[KDE, Win32] Key Manager shows an error icon when the key is empty, but present in keys.conf

### ISSUE THREAD

**Issue by DankRank** [GerbilSoft/rom-properties#121]
![rp-config key manager with error icon on the row with empty key](https://user-images.githubusercontent.com/4050457/37783202-903c04ec-2dfd-11e8-9965-30e741890a43.png)

contents of my `~/.config/rom-properties/keys.conf`:
```
[Keys]
rvl-common=[REDACTED]
rvl-korean=[REDACTED]
rvl-sd-aes=[REDACTED]
rvl-sd-iv=[REDACTED]
rvl-sd-md5=[REDACTED]
wup-vwii-common=
```

**Comment by GerbilSoft** [comment]
This also affects Win32. Probably an issue in the base KeyStoreUI class.
