### ISSUE TITLE
GBX: footer for Game Boy ROMs

### ISSUE THREAD

**Issue by Sanqui** [GerbilSoft/rom-properties#125]
http://hhug.me/gbx/1.0

A very recent standard for bootleg ROMs with incorrect (or impossible-to-be correct) headers.

**Comment by GerbilSoft** [comment]
@Sanqui I added untested support for GBX footers. I don't have any test ROMs, so I can't test it myself. Can you test it with some ROMs that have GBX footers?

**Comment by GerbilSoft** [comment]
I tested a few GBX ROMs a while ago and it does work, so I'm closing this.
