### ISSUE TITLE
gettext truncates Win32 file filters because of embedded nulls

### ISSUE THREAD

**Issue by DankRank** [GerbilSoft/rom-properties#129]
`"otp.bin\0otp.bin\0Binary Files (*.bin)\0*.bin\0All Files (*.*)\0*.*\0\0"` becomes `"otp.bin"`

fixing this is a prerequisite for having gettext support in win32 (#122)

**Comment by GerbilSoft** [comment]
Fixed by commit b315e80cdd28459afcbb6c1c0779408bbf988b83.
