### ISSUE TITLE
translatability issues

### ISSUE THREAD

**Issue by DankRank** [GerbilSoft/rom-properties#132]
This is a list my concerns/complaints/wishes related to i18n. I already told you all of this in private, but here I collected all of it together for your convenience.

tl;dr - the important stuff (for me) is (2) and the untranslatable strings (at the very bottom). (1) and (5) are simple to fix, as well as (3) (which you need to decide on whether to fix it or not). I didn't have any problems related to (4) yet, so you may leave it as it is for now, but consider doing it next refactoring.

---

- [x] (1) `"ROM Properties Page"` and `"Shell Extension"` should be merged together, along with formatting tags. Probably to something like this: `"<b>ROM Properties Page</b><br/>\nShell Extension"`

**Rationale:** in ru/uk common noun is put before the proper noun that it describes (as in "Shell Extension ROM Properties Page"). Currently the only way to do this is quite ugly:
- `"ROM Properties Page"` becomes `"</b>Shell Extension<b>"`
- `"Shell Extension"` becomes `"<b>ROM Properties Page</b>"`

**Location:** src/kde/config/AboutTab.cpp `void AboutTabPrivate::initProgramTitleText(void)`

**Notes:** 
- you might want to also merge "Version %s" with it, while you're at it

**Impact:** avoidable

---

- [x] (2) There should be possibility to swap system name and file type

**Rationale:** same reason as (1), common nouns before proper nouns in ru/uk

**Location:**
- src/kde/RomDataView.cpp `void RomDataViewPrivate::initHeaderRow(void)`
- src/win32/RP_ShellPropSheetExt.cpp `int RP_ShellPropSheetExt_Private::createHeaderRow(HWND hDlg, const POINT &pt_start, const SIZE &size)`

**Notes:**
- that code looks trash. Shouldn't systemName and fileType be guaranteed to be non-null? Replace all those extra checks with asserts, and you're good to go with `rp_sprtinf(C_("RomDataView", "%1$s\n%2$s"), systemName, fileType)`

**Impact:** bad style

---

- [x] (3) `"Copyright (c) 2016-2017 by David Korth."` shouldn't be translatable

**Rationale:** Copyright strings in Libraries tab aren't translatable, so for consistency this shouldn't be either. Also, since this is legal text (not a very important one tho, Berne convention is a thing), it's probably better to leave it untranslated.

**Location:** src/kde/config/AboutTab.cpp `void AboutTabPrivate::initCreditsTab(void)`

**Notes:**
- As an alternative, you could make other copyright strings translatable, like so `"Copyright (c) %1$s by %2$s."`
- Copyright year needs to be updated. :^)
- somewhat related: on Libraries tab, some copyright notices have (C) while others have (c).
- somewhat unrelated: you should add link to APNG homepage on libraries tab

**Impact:** consistency

---

- [ ] (4) Context for property values should be sufficient enough to differentiate strings in different fields.

**Rationale:** in ru/uk, adjectives are inflected based on noun class (grammatical gender) of the noun. Wrong inflection in constructs like "Noun: Adjective" are bad style.

**Location:** many different locations

| Status           | Subclass   | (Sub)string   | Fields                                             |
|:----------------:|:----------:|:-------------:|:--------------------------------------------------:|
| non-collision    | GameCube   | `Unknown`     | `"Publisher"` and `"Region"`                       |
| non-collision    | VirtualBoy | `Unknown`     | `"Publisher"` and `"Region"`                       |
| non-collision    | DMG        | `INVALID`     | `"Checksum"` and `"Region"`                        |
| pseudo-collision | DMG        | `"Unknown"`   | `"Game ID"`, `"ROM Size"`, `"RAM Size"`            |
| non-collision    | DMG        | `Unknown`     | `"Publisher"`, and fields listed in previous entry |

**Notes:**
- This list is not exhaustive. Just the things I found so far.
- `"non-collision"` means that the strings themselves are different, but look related. Still would recommend adding more context, or at least a tr comment, because as of right now one needs to look in the source code to see what field a string is related to.
- `"pseudo-collision"` means that there's a collision, but it's irrelevant for ru/uk, because fields are of the same noun class. Might be an actual collision for other languages.
- `"collision"` would mean that there's no ru/uk translation that can satisfy all fields. So far I've found none of those.
- Instead of doing this on a case-by-case basis, it should probably be done for all strings which are used as field values, for consistency.
- Take a look at VirtualBoy's region code: `"Japan"` and `"USA"` are in context of `"Region"`, while `"Unknown"` is in `"VirtualBoy"`. In GameCube, most regions are `"Region|GameCube"`, while the default string of `"Unknown (0x%08X)"` is in `"GameCube"`. Such inconsistencies result in some of the entries on the above list, and also increase confusion.
- There's a common pattern that functions like gcnRegionToString and NintendoPublishers follow. They return null if input is invalid/unknown, and then the caller has to format the unknown string on its own. For gcnRegionToString, this manifests in the aforementioned inconsistency. For NintendoPublishers, this creates the same exact "Unknown" string in almost all of Nintendo subclasses. I think it would make more sense to format the unknown string inside those functions, instead of returning nullptr, however, this has the disadvantage of requiring an extra string copy when input is NOT invalid/unknown (as opposed to being able to return const char*).

**Impact:** Avoidable so far for ru/uk. Might result in bad style for other languages. In absence of tr comments, requires peeking into source for context.

---

- [x] (5) string concatenation of `"(Wii U Virtual Console)"`. Should probably be formatted: `"%s (Wii U Virtual Console)"`

**Rationale:** maybe someone will want to order it differently ¯\\\_(ツ)\_/¯

**Location:** src/libromdata/Console/NES.cpp `int NES::loadFieldData(void)`

**Impact:** none in ru/uk

---

List of strings which are currently not translatable:

| File            | Where                                                | What         |
|:---------------:|:----------------------------------------------------:|:------------:|
| DMG.cpp         | `const char *const DMGPrivate::dmg_hardware_names[]` | `"Unknown"` |
| DMG.cpp         | `int DMG::loadFieldData(void)`                       | ~`"Hardware"`~ fixed |
| DMG.cpp         | 2x `int DMG::loadFieldData(void)`                    | ~`"ROM Size"`~ fixed |
| DMG.cpp         | 2x `int DMG::loadFieldData(void)`                    | ~`"RAM Size"`~ fixed |
| Nintendo3DS.cpp | 2x `int Nintendo3DS::loadFieldData(void)`            | ~`"Warning"`~ fixed  |
| Lynx.cpp        | `int Lynx::loadFieldData(void)`                      | ~`"Rotation"`~ fixed |
| Dreamcast.cpp   | `int Dreamcast::loadFieldData(void)`                 | ~`"Checksum"`~ fixed |
| NES.cpp         | `int NES::loadFieldData(void)`                       | ~`"TV Mode"`~ fixed  |
| GameCube.cpp    | `int GameCube::loadFieldData(void)`                  | ~`"Game ID"`~ fixed  |

- Many of these exist in both translatable and untranslatable forms
- "Checksum" in Dreamcast.cpp is #if 0'd
- in `int KhronosKTX::loadFieldData(void)`, the field names `"glType"`, `"glFormat"`, `"glInternalFormat"`, and `"glBaseInternalFormat"` aren't translatable, but I don't think they should be.

**Comment by GerbilSoft** [comment]
(1) still needs to be fixed for Windows, though that will be more complicated. The text is in the .rc file, but the bold attribute is in the source code, and it's done using SetWindowFont(), not markup.

Alternatively, the control IDs of the two labels can be swapped in the .rc file.

**Comment by GerbilSoft** [comment]
Closing this for now. Open another issue and/or a PR for specific translation issues.
