### ISSUE TITLE
Game audio formats (VGM, etc)

### ISSUE THREAD

**Issue by GerbilSoft** [GerbilSoft/rom-properties#153]
Add more game audio formats. Currently, ADX, GBS, and NSF are supported.

More formats to add:
* VGM: http://vgmrips.net/wiki/VGM_Specification
* ~~GYM: http://fileformats.archiveteam.org/wiki/GYM~~
* PSF and subformats: http://fileformats.archiveteam.org/wiki/Portable_Sound_Format

Note that VGM files are typically distributed in gzipped format (VGZ), so we'll need to handle decompression. (Only the header needs to be decompressed, so we don't need to load the whole file in memory.)

EDIT: GYM doesn't have any useful tags, so I probably won't add support for it.

**Comment by GerbilSoft** [comment]
More formats:

* SPC: http://vspcplay.raphnet.net/spc_file_format.txt
* SID: https://www.hvsc.c64.org/download/C64Music/DOCUMENTS/SID_file_format.txt

**Comment by GerbilSoft** [comment]
More stuff:

* GYM: http://vgmrips.net/wiki/GYM_File_Format - there's a custom tag format used by YMAMP that may or may not be present in GYM files.
* S98: http://vgmrips.net/wiki/S98_File_Format

**Comment by DankRank** [comment]
How about GBR (aka GBRF, aka Game Boy Rip Format)? It's an older format for Game Boy. Doesn't have as much of useful info though.

Documentation in jpn: http://www.geocities.co.jp/Playtown-Yoyo/6130/memo/gbrspec.txt
My own notes: https://pastebin.com/raw/rgfmA0hm

UPD: Just found an english documentation source, which does include CGB flag in TAC byte: http://www.angelfire.com/nc/ugetab/GBR_Format.txt

Files for testing can be found [here](http://snesmusic.org/hoot/gbs/) (search for `GBR`)

---

There's also something called GBS Player, a conversion of GBS into a GB ROM. There are 338 of those in GoodGBX v3.14 romset.

At the very beginning of the rom ($0000), there's a jp imm16 to the rom section of the GBS. For example, if rom starts with `C3 D0 3F`, the gbs header can be found at offset `0x3FD0-0x70 = 0x3F60` (0x70 is size of GBS header).

This technique works with all such roms in GoodGBX, and at least one GBS player ([NEZplug](http://nezplug.sourceforge.net/)) uses it to support playing back such files.

Maybe this could be supported by having DMG class check for the "GBS\1" magic at appropriate place, and then somehow use the GBS class to generate the fields onto a separate tab

**Comment by GerbilSoft** [comment]
Added GBS Player support in commit 20dd4ae918314b47ca4b9d7af832f778935f0cee.

The DMG class checks for the magic number, and if present, instantiates a GBS class and adds its fields to another tab.

**Comment by GerbilSoft** [comment]
Current status:

The following audio formats are supported:
* ADX (CRI ADPCM)
* GBS (Game Boy Sound)
* NSF (Nintendo Sound Format)
* PSF (and all subformats)
* SAP (Atari 8-bit)
* SNDH (Atari ST) (including ICE decompression, though not an optimal implementation)
  * unice68 is GPLv3 licensed, so a compile flag is provided to disable it.
* SPC (Super Famicom / SNES)
* VGM (Video Game Music; some fields aren't supported yet.)

TODO:
* VGM: Transparent gzip decompression on Windows. (See #156.)
* SNDH: Metadata export.

**Comment by GerbilSoft** [comment]
Pretty much everything is implemented for v1.4. The only things I haven't added yet from this issue are:
* GYM (default format has no metadata; some extensions add some)
* GBR (not much metadata here)

Closing this issue for now. Open new issues for each format as it shows up.
