### ISSUE TITLE
DLC WADs have no metadata shown

### ISSUE THREAD

**Issue by einstein95** [GerbilSoft/rom-properties#155]
They only seem to have one name (for a US one at least) and use WIBN instead of IMET (which is currently supported).

Wiibrew has an article on [the WIBN format](http://wiibrew.org/wiki/Savegame_Files#Banner).

Support for this can also tie into support for Wii save data.

**Comment by GerbilSoft** [comment]
Should be fixed in the feature/wii-save-file branch.

Relevant commits:
* 6d69a28493bbd6786239023314425dcc070600a7
* 74c6e03d436e90c07c0f08553104de5952698358

Note that OS metadata containing the WIBN title isn't currently exported. Will do that later.
