### ISSUE TITLE
Windows 10 - Explorer crashes when loading multi-disc gamecube games

### ISSUE THREAD

**Issue by Nomelas** [GerbilSoft/rom-properties#158]
I have my gamecube isos all in subfolders sorted by game. So multi-disc games are in their own subfolder.

When I go into one of these folders, explorer freezes then crashes and reloads.

**Comment by GerbilSoft** [comment]
Can you provide some more details?

* Which release of Windows 10? (either build number or release version, e.g. v1803)
* What version of rom-properties are you using?
* Can you provide a full subdirectory listing, starting with the top-level game directory?

I don't have access to a Windows 10 machine, so I can't debug this myself. Would it be possible for you to run the Visual Studio debugger to figure out where it's crashing? (You'll need the .pdb files, which are available on the Release page, and also VS2017 Community Edition. A source code checkout may be needed as well.)

**Comment by Nomelas** [comment]
Great, I'll test it out this evening

**Comment by Nomelas** [comment]
@GerbilSoft fixed! thanks for the quick fix :)
