### ISSUE TITLE
Suggestion: Support Standard ISO Images

### ISSUE THREAD

**Issue by cheatfreak47** [GerbilSoft/rom-properties#160]
CDs are ROMs too! 😛
It should be reasonably possible to support standard Data ISO images, right?

Some data you could put in the properties tab:
- Size
- Partition Name
- AutoPlay Label (if applicable)
- AutoPlay Icon (if applicable)

To retrieve the AutoPlay Name and Icon you need to read AutoRun.inf from the data partition on the ISO image. 

Example file:
```
[autorun]
label=My Cool Disc
icon=ICON.ICO
open=SETUP.EXE
```
So from this you'd pull the label and icon path, and then fetch the icon from the data partition as well.
The icon field often refers to an EXE, so you may need to pull the icon from the EXE as well somehow.

And of course you'd use the AutoPlay icon for the file preview in file managers and such.

If no icon definition exist, pull the icon from the "open" field. If no autorun.inf exists, you could just look for the first ICO or EXE on the disc in the root, and use it's icon instead.

You can also pull more metadata from autorun.inf in some cases if you'd like, details here:
https://en.wikipedia.org/wiki/Autorun.inf

**Comment by cheatfreak47** [comment]
Once this is done, you may be able to apply a bunch of the code from it to the partitions of other various types of disk images as well, though I'm not sure which file types at the moment, though. I'll edit this reply later with some more types you can support with something like this.

**Comment by GerbilSoft** [comment]
In progress in the feature/ISO branch. Currently supports displaying the Primary Volume Descriptor and UDF version from standard ISO images. This information is also listed as a separate tab for Sega Mega CD, Sega Saturn, and Sega Dreamcast images.

TODO:
* Metadata properties.
* Icon thumbnailing for Windows autorun.inf (and maybe others?).
* XDVDFS for Xbox and Xbox 360, with thumbnailing from default.xex.

**Comment by GerbilSoft** [comment]
Partially implemented for v1.4. Supports retrieving the PVD only. UDF and icon thumbnailing will be done later. I'll keep this issue open.

**Comment by GerbilSoft** [comment]
autorun.inf reference: https://docs.microsoft.com/en-us/windows/desktop/shell/autorun-cmds

**Comment by GerbilSoft** [comment]
ISO-9660 is implemented as of v1.4, and v1.6 adds support for High Sierra (the predecessor to ISO-9660).

That's enough to close this issue. I'll add the other pieces in other issues.
