### ISSUE TITLE
Is there any way to get nightly/ beta builds or at least a build guide?

### ISSUE THREAD

**Issue by Masamune3210** [GerbilSoft/rom-properties#165]
Title

**Comment by GerbilSoft** [comment]
I do have travis-ci and AppVeyor set up, but they aren't storing artifacts anywhere.

Compile guide: https://github.com/GerbilSoft/rom-properties/blob/master/doc/COMPILING.md

On 64-bit Windows, you only need a 64-bit build for Explorer integration. A 32-bit version is needed if you want thumbnailing when browsing folders in 32-bit programs, but it isn't essential.

**Comment by Masamune3210** [comment]
Thanks for the guide! Is there any way to start storing artifacts even temporarily, like for a week? If not, I get it

**Comment by GerbilSoft** [comment]
Need to enable build artifacts on AppVeyor.

**Comment by Masamune3210** [comment]
Artifacts seem to be enabled, closing
