### ISSUE TITLE
Incompatible with Caja

### ISSUE THREAD

**Issue by erido123** [GerbilSoft/rom-properties#181]
Running on Arch with the Mate desktop, works fine while using thunar but doesnt work while using MATE's default file manager(Caja). Although using Thunar is a fix to this problem I feel like extending support for Caja would be a more long term solution.

**Comment by GerbilSoft** [comment]
Implemented in https://github.com/GerbilSoft/rom-properties/commit/19a0394951e73d12c907694ccfd08781978671f2; finalized in https://github.com/GerbilSoft/rom-properties/commit/842b4c8f24a204b1a2a1b5a54f7f05d50b06b400.
