### ISSUE TITLE
GCN/Wii: Add support for more disc image formats.

### ISSUE THREAD

**Issue by GerbilSoft** [GerbilSoft/rom-properties#19]
<a href="https://github.com/GerbilSoft"><img src="https://avatars2.githubusercontent.com/u/6764716?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [GerbilSoft](https://github.com/GerbilSoft)**
_Tuesday Sep 20, 2016 at 14:47 GMT_
_Originally opened as https://github.com/GerbilSoft/rom-properties.reworking/issues/19_

----

There's some other formats that aren't used as much as GCM ("ISO") and WBFS, as detailed on http://wit.wiimm.de/info/iso-images.html :
- CISO: A sparse format similar to WBFS, except with a much saner header format. It's designed for use as an image format rather than a hard drive format. Supported by Dolphin Emulator.
- GCZ: Similar to CISO, but uses gzip compression. Supported by Dolphin Emulator.
- WDF: A significantly more complex sparse format than either CISO or WBFS. Not seen too often.
- WIA: An archival format that completely reoranizes the disc image. Among other things, it has its own partition layout, decrypts the Wii partitions, and uses LZMA compression. Probably won't be supported anytime soon.

**Comment by GerbilSoft** [comment]
<a href="https://github.com/GerbilSoft"><img src="https://avatars2.githubusercontent.com/u/6764716?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [GerbilSoft](https://github.com/GerbilSoft)**
_Tuesday Sep 20, 2016 at 16:35 GMT_

----

Bonus round: There's actually two formats called CISO:
1. The GameCube CISO format, which is sparse only.
2. The PSP CISO format, which is sparse and compressed.

Both have the same magic number ("CISO"), but the GameCube version has the block size immediately after, whereas the PSP version has the header size (0x18). That should make it easy to distinguish between the two.

**Comment by GerbilSoft** [comment]
<a href="https://github.com/GerbilSoft"><img src="https://avatars2.githubusercontent.com/u/6764716?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [GerbilSoft](https://github.com/GerbilSoft)**
_Friday Oct 07, 2016 at 17:47 GMT_

----

TGC support was added in commit 77bc6d255d5c732bf6324a9545d0161de90a750f. It's basically a GCM with a 32 KB header. It's commonly found in demo discs and special promo releases, e.g. Zelda Collector's Edition.

Note that TGCs usually either have the same game ID as the main GCM or the generic "RELSAB" ID, so external images are disabled for them.

**Comment by GerbilSoft** [comment]
<a href="https://github.com/mariomadproductions"><img src="https://avatars3.githubusercontent.com/u/9919020?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mariomadproductions](https://github.com/mariomadproductions)**
_Friday Feb 17, 2017 at 15:47 GMT_

----

- .iso.dec: Reversible format that is the GCN/Wii ISO minus junk data. Tool here: [NASOS](https://drive.google.com/file/d/0B_yBl-184usmbnQyTGZoRFVXOVU/view?usp=sharing). Format and tool by LedZeppelin68. I've contacted him to ask for program source/format docs.

**Comment by GerbilSoft** [comment]
<a href="https://github.com/KAMiKAZOW"><img src="https://avatars3.githubusercontent.com/u/3259076?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [KAMiKAZOW](https://github.com/KAMiKAZOW)**
_Monday May 29, 2017 at 21:09 GMT_

----

Source code for WDF is here: http://wit.wiimm.de/info/wdf.html#src

It's a bit weird but the C implementation is GPLv2+ (matching Dolphin's licensing), whereas the C++ library is GPLv**3**+. If that were to be used (because I guess it would be easier), IMO there should be a CMake option. Depening on what the maintainers say, maybe even default it to Off (if they want Dolphin not to be GPLv3+ out of the box because of "combined work" legal reasons).

**Comment by mariomadproductions** [comment]
More recently updated NASOS tool "nNASOS":
http://romshepherd.com/index.php/topic,6092.0.html

**Comment by ajshell1** [comment]
I'm a member of Redump, and I have dumped and submitted several Wii games (mostly shovelware that nobody else has bothered to dump yet). After experiencing the space saving offered by the NASOS format, I can see why it's the prefered format of most Redump contributors. While it is slightly less efficient than WBFS compression and Dolphin's own GCZ compression for Wii games, it has the distinct advantage of not being a destructive compression format.  That is, converting a GCZ or WBFS file back into an ISO will often not result in an ISO with the same checksum as the ISO used to create the GZC or WBFS file. This is not the case for the NASOS. This allows for the disc image to be preserved in a way that GCZ and WBFS does not allow, while still saving a significant amount of space.

Anyway, I like the NASOS format so much that I'm willing to pay someone to add NASOS support to Dolphin.

**Comment by GerbilSoft** [comment]
@mariomadproductions That forum requires registration. Is the executable and/or source available to download on a public site?

I may consider adding NASOS support to rom-properties 1.3, and if the resulting file is comparable to CISO, maybe Nintendont as well.

**Comment by mariomadproductions** [comment]
The source doesn't seem to have been released for NASOS. And the author of nNASOS says that the source for it hasn't been released. [Here](https://drive.google.com/file/d/1eT2ZfKZ7XYGCAkXfylWyrPnQC-W4SCj1/view?usp=sharing) is a build of nNASOS 1.71. But I have asked the author of the latter to release it publicly (or at least send it to you).

**Comment by mariomadproductions** [comment]
The author of the original NASOS appears to be active in this thread:
http://forum.redump.org/topic/17831/nasos-2/

**Comment by GerbilSoft** [comment]
Closing for 1.4, since most of these formats have been implemented.

Will open a new issue for the remaining formats.
