### ISSUE TITLE
rp-config doesnt actually write anything to the keys.conf file

### ISSUE THREAD

**Issue by Masamune3210** [GerbilSoft/rom-properties#192]
When adding keys or importing keys using rp-config, the app doesnt actually write anything out to the keys.conf file. When keys are added manually to the file, they appear in the app, but any new keys are still not added to the file. Using Process Explorer, it looks like the program isnt even trying to write to the file, only opening the file and querying information, only to close it a second later

**Comment by GerbilSoft** [comment]
I'm unable to reproduce this on either Linux (KDE5) or Windows 7.

What version of Windows are you using? I suspect Microsoft may have done some weird stuff with WritePrivateProfileString() in Windows 10, since it's considered a "deprecated" function.

**Comment by Masamune3210** [comment]
I'm on 10, would test on 8 and 7 but my computer is currently out of commission :(

Version 1903 Build 18362

**Comment by GerbilSoft** [comment]
I have a copy of LTSC 1809 available, I'll test it out sometime tomorrow.

**Comment by DankRank** [comment]
Works fine on my side. Version 1709 (OS Build 16299.579)
Are you sure you're clicking OK/Apply and not just closing the window with 🗙?

**Comment by Masamune3210** [comment]
Yes, I'm clicking ok and not just leaving the window. Found out that manually entering the key will save, but anything involving copy\paste or importing keys will not

**Comment by GerbilSoft** [comment]
Just tested importing keys on the Linux build, and it seems that if you import e.g. boot9.bin, then click Apply, it acts like it wrote it, but it didn't. Manually changing any other key, *then* clicking Apply ends up saving *all* of them.

Fixing this now and will prepare a v1.4.1 at some point today.

**Comment by GerbilSoft** [comment]
Can't seem to reproduce the copy/paste issue, but the import issue is fixed now locally. Will push changes soon.

**Comment by GerbilSoft** [comment]
@deadair3210 If you can, please test this and check if it fixes the issues. I couldn't reproduce the copy/paste problem, but the .bin import should be fixed.

**Comment by Masamune3210** [comment]
Where do I get it, if it needs to be built could someone build it please? Can't build things right now....

**Comment by DankRank** [comment]
Here's a build of cbe762ac314e12f2e515ca729c6fc5ec6bd7b374
[rom-properties_1.4-windows.zip](https://github.com/GerbilSoft/rom-properties/files/3575724/rom-properties_1.4-windows.zip)
[rom-properties_1.4-windows.debug.zip](https://github.com/GerbilSoft/rom-properties/files/3575727/rom-properties_1.4-windows.debug.zip)

**Comment by Masamune3210** [comment]
Will test and update this post when I get home from work

**Comment by Masamune3210** [comment]
It successfully writes the keys to the file when importing my boot9 dump so I'm going to assume that it works for the others as well! Thanks!

**Comment by DankRank** [comment]
What about the copy/paste issue you mentioned in
https://github.com/GerbilSoft/rom-properties/issues/192#issuecomment-527178956
? (I honestly have no clue how is that any different than manually entering
the keys)

**Comment by Masamune3210** [comment]
Couldn't reproduce the issue, I think my laptop was just being buggy at the time

**Comment by GerbilSoft** [comment]
Fixed in v1.4.1. Binaries should be uploaded soon.
