### ISSUE TITLE
certain games crash explorer when moused over or selected

### ISSUE THREAD

**Issue by DessertArbiter** [GerbilSoft/rom-properties#195]
prince of persia: sands of time for gamecube is one example

**Comment by GerbilSoft** [comment]
This indicates a bug with the metadata handler that was added in v1.4. I don't have a copy of this game offhand; I'll get a copy and see if I can reproduce this issue.

**Comment by GerbilSoft** [comment]
Reproduced this on Windows 7, but not on KDE. (Though KDE isn't showing the disc image metadata for some reason...)

**Comment by GerbilSoft** [comment]
Fixed in master; will cherry-pick this fix (and a fix for some Xbox 360 games) into the 1.4 branch and release v1.4.2.
