### ISSUE TITLE
Windows UI has no scroll bar

### ISSUE THREAD

**Issue by InternalLoss** [GerbilSoft/rom-properties#204]
When on a long UI that needs a scroll (for example, some tabs in XEX's menus), no scroll bar occurs, and the tab doesnt respond to any scrolling attempts
![](https://i.imgur.com/EmwHUJw.png)

**Comment by GerbilSoft** [comment]
Vertical scrolling is implemented now. Still need to adjust a few things, including control widths if a vertical scrollbar is displayed, and maybe a horizontal scrollbar.

**Comment by Masamune3210** [comment]
Awesome, will test when I get home

**Comment by Masamune3210** [comment]
Awesome, will test when I get home

**Comment by Masamune3210** [comment]
Seems to be working fine! Horizontally stuff still spills out of the frame sometimes, as you already noted but that only would be a problem for really long strings or if anything is placed too right in the sheet

**Comment by GerbilSoft** [comment]
Closing this for now. Adjusting ListViews and/or for horizontal scrolling will be done later.
