### ISSUE TITLE
Make this a DE-independend thumbnailer on Linux

### ISSUE THREAD

**Issue by V10lator** [GerbilSoft/rom-properties#205]
A thumbnailer on Linux is defined by xdg and doesn't need to know what DE it runs in.

Quick&dirty googles specs (you might want to google for youself to find them from xde) : https://wiki.gnome.org/DraftSpecs/ThumbnailerSpec

Arch Linux docs for the files in /usr/share/thumbnailers: https://wiki.archlinux.org/index.php/PCManFM#Get_thumbnails_for_other_file_types

Example thumbnailers with source codes: https://github.com/dirkvdb/ffmpegthumbnailer
https://github.com/GNOME/libgsf/tree/master/thumbnailer

I already see you telling this needs to know the DE cause of the settings panel but you could extend that panel into a standalone app. Also you're not including the panel for all supported DEs so a standalone app would solve issues there, too.

**Comment by GerbilSoft** [comment]
The XFCE thumbnailer uses the D-Bus thumbnailer specification. XFCE's the only major desktop that actually implements it.

GNOME and KDE use their own systems. They all use the same format for `~/.cache/thumbnails/`, though.

EDIT: The PCManFM and libgsf examples you linked use the GNOME setup, not the Thumbnailer D-Bus service. Even though the specification is hosted on GNOME's website, as far as I know, they aren't actually using it.

**Comment by GerbilSoft** [comment]
Closing since v1.6 has a mostly desktop-independent GTK+ 3.x plugin. (It supports Nautilus, Caja, Nemo, and Thunar.)
