### ISSUE TITLE
Win32 thumbnailer crashes on locked files

### ISSUE THREAD

**Issue by DankRank** [GerbilSoft/rom-properties#207]
v1.4.3, Windows 10 1709
When I open my user profile and scroll down, COM Surrogate crashes.
![image](https://user-images.githubusercontent.com/4050457/70405897-71a72100-1a47-11ea-8698-44689f7f3e46.png)
Through filtering, I narrowed it down to `NTUSER.DAT`.

Here's the stack trace: [thumbnailercrashstacktrace.txt](https://github.com/GerbilSoft/rom-properties/files/3937804/thumbnailercrashstacktrace.txt)

`RP_ThumbnailProvider_Private` dtor calls `file->unref();` with null `file`, which leads to the crash.

The most likely possibility is that `RP_ThumbnailProvider::Initialize` fails to open the file, and returns E_FAIL [here](https://github.com/GerbilSoft/rom-properties/blob/v1.4.3/src/win32/RP_ThumbnailProvider.cpp#L95-L99), without ever setting the `file` member. Or maybe `Initialize` simply never gets called. In any case, the destructor should check for null `file` before trying to free it.

The reason why it fails to open `NTUSER.DAT` is because system opens it without `FILE_SHARE_READ` flag. I've managed to reproduce it on other files with this: [lock.c](https://github.com/GerbilSoft/rom-properties/files/3937861/lock.c.txt)

**Comment by GerbilSoft** [comment]
`file` is initialized using new, so it can't ever be NULL on modern systems.

I tested using a debug build (which disables the COM Surrogate and runs in-process), and Explorer crashes. Will find the source and commit a fix.
