### ISSUE TITLE
No icon on some 3DS games even with all keys present and valid.

### ISSUE THREAD

**Issue by SanktyRG** [GerbilSoft/rom-properties#208]
Yeah, pretty much what title says, I'm on Ubuntu 18.04 using Nautilus file browser, some icons work perfectly and some games just show no icon at all, like when the keys are missing or bad, but I have verified them all and the GUI shows the green check on them all.

It's also worth noting I've also tried wiping thumbnail data in cache and restarted both Nautilus and my Computer.

**Comment by cheatfreak47** [comment]
I can't confirm this exact same problem on Windows, but I can confirm it specifically for properly encrypted DLC packages, on the latest release version.

**Comment by GerbilSoft** [comment]
For the DLC CIAs: The NCCHReader class was verifying encryption keys by checking that the first file in the ExeFS was named `.code`. This is correct for CXIs, but not for CFAs (which are used by DLCs); for CFAs, the first file is "icon".

@felixsrg Can you try compiling the latest code from the master branch and see if that fixes your issue? If not, please post `rpcli` output from the CIA files that aren't being thumbnailed correctly.

**Comment by SanktyRG** [comment]
I finally got the time to compile it, I'm sorry for the delay.

After compiling, all the icons started showing up correctly again, for encrypted and decrypted base, updates and DLCs.

**Comment by GerbilSoft** [comment]
Thanks for confirming that it's fixed. Closing this bug.

If you encounter any other CIAs (or other 3DS files) that aren't thumbnailing properly, please file another bug and include the `rpcli` output.
