### ISSUE TITLE
Windows 7 explorer crashes constantly after installing rom propreties

### ISSUE THREAD

**Issue by Midou36O** [GerbilSoft/rom-properties#217]
![image](https://i.imgur.com/D4Fk2y0.png)
Apparently the rom propreties.dll crashes right after explorer.exe starts up, and it keep restarting then crashing.

**Comment by GerbilSoft** [comment]
There's not enough information in this preview. I'd need the full error details, including the module base address.

This usually indicates that there's a particular file on the desktop that's causing issues. Can you try narrowing it down to one file? (after getting the full error details)

**Comment by Midou36O** [comment]
I'm sorry if i don't get all what you meant as i'm not a native english speaker, i hope the module base is in the previews below:
![image](https://user-images.githubusercontent.com/45198486/81404220-8128b400-9124-11ea-835f-30a428c80a97.png)
![image](https://user-images.githubusercontent.com/45198486/81404289-a289a000-9124-11ea-9739-cb327fafb6d4.png)
![image](https://user-images.githubusercontent.com/45198486/81404303-aae1db00-9124-11ea-999e-a8e68d899961.png)

Also, i tried what you told me to do and it worked, the file that caused this issue is a shortcut file that redirects to a deleted ISO file:
![image](https://user-images.githubusercontent.com/45198486/81405363-03b27300-9127-11ea-951a-575ca7aae278.png)
![image](https://user-images.githubusercontent.com/45198486/81405390-0c0aae00-9127-11ea-99aa-26c23590cbb2.png)

**Comment by GerbilSoft** [comment]
That actually narrows it down quite a bit. (I haven't done much with Windows shortcuts, so I haven't encountered this myself.)

Reopening this so it can be fixed for 1.6 and/or 1.5.1.

**Comment by GerbilSoft** [comment]
Fixed for 1.6.
