### ISSUE TITLE
Feature Request: Return PlayStation/PlayStation 2 executable build dates and filenames from ISO/BIN image

### ISSUE THREAD

**Issue by ehw** [GerbilSoft/rom-properties#222]
Every PS1/PS2 game will have an executable that is named after the game's designated product code (some games will either have that or an .ELF file). In other words, the filename for the game's executable will vary from game to game. However, every PS1/PS2 game has a system.cnf file at the root of each disc. This file specifies the default executable to launch at startup. As far as I know, each system.cnf that originates from a disc will always have a line that contains ""BOOT2 = cdrom0:\", which contains the filename for the default executable followed by a semicolon. Is it possible to use this to determine the build date and filename of the main executable that's used in each PS1/PS2 game?

**Comment by GerbilSoft** [comment]
PS1 and PS2 have been on the TODO list for a while. I just haven't gotten around to really digging through them to get the useful information and/or icons.

**Comment by GerbilSoft** [comment]
Merged for 1.6.
