### ISSUE TITLE
Common icons for games that don't show thumbnails

### ISSUE THREAD

**Issue by Amnesia1000** [GerbilSoft/rom-properties#225]
Many of my 3DS games (Cia and 3DS format) don't show thumbnails, would there be chances that rom-properties shows a common icon (for example the 3DS cartridge) for roms that don't have thumbnails? Not only for 3DS but for all supported consoles.

**Comment by GerbilSoft** [comment]
I've been considering it, but I don't have generic stock icons for these. Contributions are welcome.

**Comment by Amnesia1000** [comment]
Could help with that, I'm not a designer or good using image design programs but I could see if I find images of free Disks/cartridges to use in rom-properties. I have some that I use to put on my games.
[Some Icons.zip](https://github.com/GerbilSoft/rom-properties/files/4816663/Some.Icons.zip)

**Comment by GerbilSoft** [comment]
There's actually an existing issue for this: #81 (Generic icons for ROM images that don't have any icons or thumbnails).

Still not entirely sure how we'd implement this, and I'd probably want to use more "generic" icons that can be scaled more easily (e.g. SVG icons).
