### ISSUE TITLE
Feature Request: Report CDVDGEN metadata from PS2 prototypes

### ISSUE THREAD

**Issue by ehw** [GerbilSoft/rom-properties#227]
From what I discussed with GerbilSoft and what I wrote here:

http://forum.redump.org/topic/29351/ps2-cdrdvdr-prototypes-cdvdgen-metadata/

Each PlayStation 2 development disc authored with CDVDGEN contains metadata that is independent from the usual volume descriptors. This data does not exist in commercial games as far as I know, and even games that are a perfect match for the final will contain this metadata if an equivalent exists on a DVD-R/CD-R.

The metadata appears in different places depending if the game were authored for a DVD-R or a CD-R. In DVD-Rs, this information starts at offset $7000 in every .BIN/.ISO dump. In CD-Rs, this data appears to start at offset $80B8. The data at these offsets seem to consist of the following:

![image](https://user-images.githubusercontent.com/885618/85482989-03185380-b592-11ea-9f95-466ba9970b06.png)

$0 - Disc Name (size $20 bytes? usually product code)
$20 - Producer Name (size $20 bytes)
$40 - Copyright Holder (size $20 bytes)
$60 - Creation Date (size $8 bytes)
$68 - "PlayStation Master Disc 2.0", never seen anything else in this field but the version number could change I suppose. (size $1b)
$81 - ***not sure what this is*** (size $27f)
$3000 - Drive information, doesn't seem consistent so possibly treated as one string  (size $30)
$3030 - CDVDGEN version (size $C)

Then this data is repeated once more with no variation as it seems. Then it goes into the normal volume description stuff.

I've checked many PS2 prototypes, and this seems fairly consistent enough to rely on hard coded offsets. I suppose the tricky part is determining if the game is CD based or DVD based, as that will determine which offset the information starts at. It seems that the string "PlayStation Master Disc" existing at $7068 for DVD-Rs and $8120 for CD-Rs might be a good way to check, as it doesn't seem like this is something a user who's authoring the disc can change.

It'd be great to have this as no existing software else seems to look for this information, as it's specific to PS2 games. We could use this information to detail the actual creation date of the master itself, the producer in charge, and some potentially vital information about the drive/bios/version of CDVDGEN used to create the disc (if there are any quirks to speak of).

Ask me if you need to see some sample prototypes.

**Comment by GerbilSoft** [comment]
$7000 is LBA 14 in 2048-byte sector images. $80B8 is also LBA 14 but in 2352-byte sector images.

Will look into adding this as a "CDVDGEN" tab if detected.

**Comment by ehw** [comment]
Testing the latest commits on my prototype set. Everything works great. :)

**Comment by GerbilSoft** [comment]
Closing as this is implemented in v1.6.
