### ISSUE TITLE
Minimize button doesn't work on win32 rp-config

### ISSUE THREAD

**Issue by DankRank** [GerbilSoft/rom-properties#229]
rom-properties 1.5
Windows 8.1 x64
Windows 10 1507 x64
Windows 10 1909 x64
Windows 10 2004 x64
![AxGS38VarG](https://user-images.githubusercontent.com/4050457/85644731-7f995800-b6a0-11ea-8321-582d704611e2.gif)

**Comment by GerbilSoft** [comment]
Can't reproduce this on Windows 7 SP1 64-bit. Will try on Win10 1809 LTSC 64-bit over the weekend.

**Comment by cheatfreak47** [comment]
can confirm this issue as well, running Windows 10 Pro x64 2004

**Comment by DankRank** [comment]
Fixed, thanks
