### ISSUE TITLE
MIME type rework broke installation of .thumbnail files

### ISSUE THREAD

**Issue by Amnesia1000** [GerbilSoft/rom-properties#234]
Failed to install on system. (sudo make install)
Linux Manjaro Gnome (GTK3)

Error:

git_version.sh: Output is unchanged, keeping /run/media/amnesia/Datos/Builds/rom-properties/build/git_version.h
[  0%] Built target git_version
[  1%] Built target translations
[  2%] Built target mspack
[  2%] Built target rpthreads
[  4%] Built target unixcommon
[  5%] Built target inih
[  6%] Built target pvrtc
[  7%] Built target rpsecure
[  8%] Built target i18n
[  9%] Built target cachecommon
[ 11%] Built target rpcpu
[ 25%] Built target rptexture
[ 29%] Built target rpfile
[ 39%] Built target rpbase
[ 41%] Built target rp-download
[ 42%] Built target unice68_lib
[ 81%] Built target romdata
[ 84%] Built target rpcli
[ 85%] Built target glibresources
[ 90%] Built target rom-properties-xfce
[ 95%] Built target rom-properties-gtk3
[ 98%] Built target rp-thumbnailer-dbus
[100%] Built target rp-stub
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /usr/share/locale/ru/LC_MESSAGES/rom-properties.mo
-- Up-to-date: /usr/share/locale/uk/LC_MESSAGES/rom-properties.mo
-- Up-to-date: /usr/share/locale/pt/LC_MESSAGES/rom-properties.mo
-- Up-to-date: /usr/libexec/rp-download
-- Up-to-date: /etc/apparmor.d/usr.libexec.rp-download
-- Up-to-date: /usr/lib/debug/libexec/rp-download.debug
-- Up-to-date: /usr/bin/rpcli
-- Up-to-date: /etc/apparmor.d/usr.bin.rpcli
-- Up-to-date: /usr/lib/debug/usr/bin/rpcli.debug
CMake Error at src/gtk/cmake_install.cmake:41 (file):
  file INSTALL cannot find
  "/run/media/amnesia/Datos/Builds/rom-properties/src/gtk/rom-properties.thumbnailer":
  No such file or directory.
Call Stack (most recent call first):
  src/cmake_install.cmake:54 (include)
  cmake_install.cmake:44 (include)

make: *** [Makefile:139: install] Error 1

**Comment by Amnesia1000** [comment]
I leave here the pastebin of the cmake result, in case any dependency is missing

https://pastebin.com/gcwzh3CZ

**Comment by GerbilSoft** [comment]
I removed the ${CMAKE_CURRENT_BINARY_DIR} from the XDG file installation because I figured it'd be inferred. Guess not.

Should be fixed in master.

**Comment by Amnesia1000** [comment]
Fixed
