### ISSUE TITLE
Crashes on Inside exe

### ISSUE THREAD

**Issue by mariomadproductions** [GerbilSoft/rom-properties#235]
Explorer crashes when I open the rom-properties tab for the exe for the game [Inside](https://en.wikipedia.org/wiki/Inside_(video_game)) (from the Epic Games store).
Other exes work.

```
Filename: INSIDE.exe
Size: 17221632
SHA256: 09640C185C6EC66A8CEB38F06CEFCC319C232AC1066F65BDDE0891BB7A32D990
```

I can upload the exe here or DM it to you if you want.

**Comment by GerbilSoft** [comment]
You can contact me via email. (Email address is in the raw git commits.)

**Comment by mariomadproductions** [comment]
Sent you a message.
