### ISSUE TITLE
Opening ROM Properties tab causes crash of Explorer process

### ISSUE THREAD

**Issue by Masamune3210** [GerbilSoft/rom-properties#236]
Attempting to open the ROM Properties tab in the Properties sheet of any ROM causes the current Explorer process to crash

**Comment by Masamune3210** [comment]
This is on 1.6, btw
![image](https://user-images.githubusercontent.com/1053504/87260070-3b1a0480-c475-11ea-94ba-8626d84bad02.png)

**Comment by makhowastaken** [comment]
Same thing here, v1.6 on Windows 10 Pro 2004

I tested in particular with GB and GBA ROMs, both crash explorer. I uninstalled 1.5, restarted my PC, deleted the folder, installed 1.6, restarted my PC, and the ROM Properties tab still crashes explorer. Thumbnails were working great though. Rolled back to 1.5 with the same method and ROM Properties tab is working again.

Event Viewer:

Faulting application name: explorer.exe, version: 10.0.19041.329, time stamp: 0xb584d6c9
Faulting module name: rom-properties.dll, version: 1.6.0.0, time stamp: 0x5f0b7cb7
Exception code: 0xc0000005
Fault offset: 0x000000000000a813
Faulting process id: 0x3a38
Faulting application start time: 0x01d658aec1cc99ab
Faulting application path: C:\WINDOWS\explorer.exe
Faulting module path: C:\rom-properties_1.6-windows\amd64\rom-properties.dll
Report Id: 5156d091-baf3-4633-a036-f7e041f5ed37
Faulting package full name: 
Faulting package-relative application ID:

**Comment by makhowastaken** [comment]
I tested in particular with GB and GBA ROMs, both crash explorer. I uninstalled 1.5, restarted my PC, deleted the folder, installed 1.6, restarted my PC, and the ROM Properties tab still crashes explorer. Thumbnails were working great though. Rolled back to 1.5 with the same method and ROM Properties tab is working again.

**Comment by Icesythe7** [comment]
Same as the 2 above, Win 10 pro

**Comment by GerbilSoft** [comment]
I guess this is what happens when I don't do enough Windows testing. :) (I really need to add some UI test suites sometime...)

Will check this and post a v1.6.1 build for Windows if I can reproduce it.

**Comment by GerbilSoft** [comment]
Reproduced it on Windows 7, building v1.6.1 now.

**Comment by GerbilSoft** [comment]
v1.6.1 is posted, install it and it'll fix the crash problem.
