### ISSUE TITLE
[Suggestion] Support NES via iNES headers

### ISSUE THREAD

**Issue by cheatfreak47** [GerbilSoft/rom-properties#24]
Documentation on iNES headers can be found here:
http://wiki.nesdev.com/w/index.php/INES

and NES 2.0 
http://wiki.nesdev.com/w/index.php/NES_2.0

**Comment by GerbilSoft** [comment]
IIRC @DankRank was working on that. It won't be supported until at least after the initial release.

**Comment by DankRank** [comment]
Can confirm, was working on iNES but then decided to do GameBoy first. I will work on it right after the 0.8 release

**Comment by GerbilSoft** [comment]
https://github.com/GerbilSoft/rom-properties/tree/merge/DankRank/feature/ines

Current work branch. Supports iNES, NES 2.0, FDS, TNES (3DS VC), and TDS (3DS VC FDS).

Still needs some more fields for the various formats, but is mostly done.
