### ISSUE TITLE
Broken Thunarx-3 symlink

### ISSUE THREAD

**Issue by bell07** [GerbilSoft/rom-properties#244]
After installation the thumbnailer does not work in xfce / thunar
The relative symlink 
```
ls -l /usr/lib64/thunarx-3/rom-properties-gtk3.so
lrwxrwxrwx 1 root root 52 27. Jul 22:02 /usr/lib64/thunarx-3/rom-properties-gtk3.so -> lib64/nautilus/extensions-3.0/rom-properties-gtk3.so

```
is broken. Changing the symlink to absolute 

```
$ rm /usr/lib64/thunarx-3/rom-properties-gtk3.so
$ ln -s /usr/lib64/nautilus/extensions-3.0/rom-properties-gtk3.so /usr/lib64/thunarx-3/rom-properties-gtk3.so

$ ls -l /usr/lib64/thunarx-3/rom-properties-gtk3.so
lrwxrwxrwx 1 root root 57  2. Aug 09:48 /usr/lib64/thunarx-3/rom-properties-gtk3.so -> /usr/lib64/nautilus/extensions-3.0/rom-properties-gtk3.so
```
solves the issue

**Comment by GerbilSoft** [comment]
It's probably missing a ${CMAKE_INSTALL_PREFIX} in the build scripts. I'll take a look.

EDIT: Do you have libthunarx-3-dev installed? If not, install it and redo the CMake build. That should ensure the correct directory is selected. I'll add ${CMAKE_INSTALL_PREFIX} to the fallback path in addition.

EDIT 2: Also make sure you specify `-DCMAKE_INSTALL_PREFIX=/usr`.

**Comment by bell07** [comment]
Thank you! The issue is solved, I added the patch to my [Gentoo ebuild](https://github.com/bell07/gentoo-bell07_overlay/tree/master/media-plugins/rom-properties) and now the installation is working. Second issue I have is the thumbnails are not shown but I need to consider existing reports
