### ISSUE TITLE
Ram banks incorrect?

### ISSUE THREAD

**Issue by Icesythe7** [GerbilSoft/rom-properties#246]
I believe the ram banks are incorrect in gameboy games like pokemon blue for example says 32 KiB (2 banks) yet nothing even has 2 banks that I'm aware of 
` 00h - None
 01h - 2 KBytes
 02h - 8 Kbytes
 03h - 32 KBytes (4 banks of 8KBytes each)
 04h - 128 KBytes (16 banks of 8KBytes each)
 05h - 64 KBytes (8 banks of 8KBytes each)`
pokemon blue should be 32kb 4 banks.

**Comment by GerbilSoft** [comment]
Not sure now that happened, but you're right: the SRAM bank size is 8 KB, not 16 KB.
