### ISSUE TITLE
Possible to add scrollbars to information screens long enough to need them

### ISSUE THREAD

**Issue by Masamune3210** [GerbilSoft/rom-properties#251]
On some screens like the PE info for Xbox 360 ISO's, the information can be cut off and as far as  I can tell there is no way to scroll the screen to read the extra information. Is it possible to add a scrollbar to screens needing it?

**Comment by GerbilSoft** [comment]
I'm not aware of a simple "scroll view" control on Windows that would make this easily doable without redesigning a good chunk of RP_ShellPropSheetExt. It's still something that should be done at some point.

There was another issue opened for this, #204, so I'm going to mark this as a duplicate.
