### ISSUE TITLE
Not all Xbox 360 ISO's detected and treated correctly

### ISSUE THREAD

**Issue by Masamune3210** [GerbilSoft/rom-properties#253]
I have currently 4 ISO's that rom-properties fails to detect as X360 ISO's, falling back to detecting the DVD partition only. Is there a way I could turn on a log or something so I can see why its failing to detect? Or provide you info about them to help it get fixed?

**Comment by GerbilSoft** [comment]
Which disc images are these? If possible, run [abgx360](http://www.abgx360.cc/) and attach the output here.

There's currently no debug output option to log detection information, though that would be a good idea for debugging. (It'd make things slower in the UI though, so maybe only for rpcli.)

**Comment by Masamune3210** [comment]
Will do when I get home

**Comment by Masamune3210** [comment]
![image](https://user-images.githubusercontent.com/1053504/93156377-9f538180-f6cd-11ea-9f81-3ec9cd5b34d3.png)
The only thing I can figure out that makes them different than the others is they have different ISO-9660 metadata, they all still check out in abgx though so idk
[results.zip](https://github.com/GerbilSoft/rom-properties/files/5222042/results.zip)

**Comment by GerbilSoft** [comment]
These are all XGD3 discs. I'm currently using a heuristic for XGD3, since XGD3 video partitions are all unique (not related to a particular wave), and that heuristic is failing here.

Can you post the first 64 KB of each disc image here? (I'm not sure of a good utility on Windows to do this. On Linux, you can use `head --bytes=65536`.) [Compress all of the disc image headers in an archive first.]

**Comment by Masamune3210** [comment]
[headers.zip](https://github.com/GerbilSoft/rom-properties/files/5222167/headers.zip)
Pretty sure I did it right, let me know if I messed something up, I'm a bit rusty in terminal lol

**Comment by GerbilSoft** [comment]
All of those headers have the PVD creation timestamp `2014030616000000\xE0`. The XGD3 code is checking for a timestamp of 2011/01/01 or later, with timestamp "16:00:00" and timezone 0xE0. That matches here...

There's probably something else that's being misdetected. I'll have to get a copy of this disc later.

**Comment by Masamune3210** [comment]
These copies are one to one with the md5 of the copy on the-eye if that helps at all, already checked to make sure I didnt have a bad rip

**Comment by GerbilSoft** [comment]
Turns out it was an incorrect check for the `16000000\xE0` timestamp. `memcmp()` returns 0 if the values match, but I forgot the `!`.

**Comment by Masamune3210** [comment]
Just checked the build, it works great, Thanks!
