### ISSUE TITLE
[Windows] Explorer crash when trying to load certain PS1 images

### ISSUE THREAD

**Issue by TwilightSlick** [GerbilSoft/rom-properties#258]
Whenever I try to open up a folder containing a PS1 image, primarily one that does not have a "SYSTEM.CNF" file inside its file system where the main executable just says "PSX.EXE" (some examples include some prototype games and a few early Japanese retail releases) the Explorer window immediately crashes upon opening the folder.

It has happened since the Explorer file handle leak bug was fixed, and has been reproduced on the current 1.7.1 version.

Some examples from the Redump set where this bug occurs for reproduction:
-Superman (USA) (Proto)
-Aeon Flux (USA) (Proto)
-Deuce (USA) (Proto)
-Ridge Racer (Japan)
-Motor Toon Grand Prix (Japan) (Rev 1)
-Hermie Hopperhead - Scrap Panic (Japan)

**Comment by GerbilSoft** [comment]
Reproduced locally (affects all platforms); will fix this tonight and release a v1.7.2 point release.
