### ISSUE TITLE
Roms GCZ do not show thumbnails of any kind

### ISSUE THREAD

**Issue by Amnesia1000** [GerbilSoft/rom-properties#262]
The GameCube roms in GCZ format do not show thumbnails in windows (in linux only showed some), like the Wii roms in GCZ format (although I think in wii is not implemented)
<img width="2880" alt="Captura de pantalla 2020-09-24 144932" src="https://user-images.githubusercontent.com/45115804/94180969-30b4b780-fe75-11ea-890f-2f3f91760211.png">

**Comment by GerbilSoft** [comment]
.gcz (and also .rvz) weren't being registered. Will release a v1.7.2 point release tonight.

**Comment by Amnesia1000** [comment]
Great!

**Comment by Amnesia1000** [comment]
Now, as in linux, it only shows some thumbnails, not all.
![Captura de pantalla 2020-09-25 001046](https://user-images.githubusercontent.com/45115804/94222428-b2333680-fec3-11ea-9686-e59a61ec2341.png)

I have downloaded all the Wii/Gamecube covers from gametdb and placed them in their respective folders (in case it was a problem with the server or the internet) but it still does not show them.

But only GameCube roms, Wii roms (gcz) work perfectly

**Comment by GerbilSoft** [comment]
I'm unable to reproduce this here with the same disc images in GCZ format. (converted using Dolphin 5.0-12528)

If possible, can you find the smallest example that's not thumbnailing correctly and send me an email with e.g. a Google Drive link?

**Comment by Amnesia1000** [comment]
No problem, I'll upload it. The strange thing about this problem is that previously it worked correctly, in linux and windows I could see the banners of all the GC roms.

https://drive.google.com/file/d/1grmz611lginhPkLtFuYw0P0KEjC9Ch-X/view?usp=sharing

**Comment by GerbilSoft** [comment]
That GCZ image isn't being properly detected by rpcli, but dolphin-emu shows it correctly. Will take a look and figure out what's going on here.

**Comment by Amnesia1000** [comment]
Ok, in version 1.6.1 it worked fine, some changes in these versions effect that is not shown.

**Comment by GerbilSoft** [comment]
Please test the AppVeyor build before I release v1.7.3:
https://ci.appveyor.com/project/GerbilSoft/rom-properties/builds/35415277

**Comment by Amnesia1000** [comment]
Now works

**Comment by GerbilSoft** [comment]
I'll push a 1.7.3 build at some point this weekend then.
