### ISSUE TITLE
Feature Request : Extend Xbox support to ISO

### ISSUE THREAD

**Issue by Masamune3210** [GerbilSoft/rom-properties#268]
Currently when examining the properties of a Xbox ISO, all you get is Disc Type: Extracted XDVDFS and the timestamp of the iso creation, possibly add a tab to examine the exe like other iso formats and maybe the icon from the exe?

**Comment by Masamune3210** [comment]
Ignore me, im daft and made the iso wrong

**Comment by GerbilSoft** [comment]
That happens if your disc image only has the XDVDFS partition and not the DVD Video partition.

**Comment by Masamune3210** [comment]
Thanks, was wondering what I missed

**Comment by GerbilSoft** [comment]
...though it should show the icon of default.xex/default.xbe if it's present.
