### ISSUE TITLE
Checking the properties of xam.xex has a warning that says that the key is missing

### ISSUE THREAD

**Issue by Masamune3210** [GerbilSoft/rom-properties#273]
I'm assuming this file is just missing the normal information which is confusing the extension and making it assume that the decryption failed, either that or I'm all wrong and decryption is actually failing

**Comment by Masamune3210** [comment]
![image](https://user-images.githubusercontent.com/1053504/95340540-e8d15f80-087a-11eb-9b3e-d89b34484a43.png)

**Comment by GerbilSoft** [comment]
I'm not sure what exactly xam.xex is. The encryption check verifies that the encrypted data is a valid PE executable, so if this XEX doesn't have a PE executable, it'll show that warning.

Can you either post or send me a copy of xam.xex so I can examine it?

**Comment by Masamune3210** [comment]
Its part of the firmware for the 360, I believe its either the kernel or something equally special, hence the erring on file difference more than error. As its part of the firmware, its copyright so I'm not sure the best way to send it to you would be. You can find it if you extract a software update if you want to get it that way, the one I got it from was Dashboard 1888

**Comment by Masamune3210** [comment]
Or just let me know how to send it to you and i will
