### ISSUE TITLE
Add support for gpd files (Xbox 360)

### ISSUE THREAD

**Issue by Masamune3210** [GerbilSoft/rom-properties#274]
GPD files are Game Profile Data, they store the game-specific data for a profile, such as achievements, avatar awards and the like from my research. Maybe parse the game they are from and any contained items?

**Comment by GerbilSoft** [comment]
I have some initial GPD parsing locally that handles the main string and achievements. Achievement icons might not show up because most GPD files don't actually have them, and a few don't have a main icon either.

**Comment by GerbilSoft** [comment]
Mostly implemented. Avatar Awards aren't parsed yet, and it doesn't check if an achievement is unlocked or not. I'll need to verify unlock status with my own save files at some point.

**Comment by GerbilSoft** [comment]
Since GPD was implemented for the most part in v1.8, I'm closing this issue as done.
