### ISSUE TITLE
Marble Blast DLC file is incorrectly parsed

### ISSUE THREAD

**Issue by Masamune3210** [GerbilSoft/rom-properties#276]
I have a feeling its not supposed to be this way, let me know if you need the file sent to you. Same issue with the firmware though since its copyright
![image](https://user-images.githubusercontent.com/1053504/95362880-5c339b00-0894-11eb-8a5b-cf545d09c208.png)

**Comment by Masamune3210** [comment]
Icon is missing too, just noticed

**Comment by GerbilSoft** [comment]
Please send this and the other files that are having issues via email, and/or email me a Google Drive link.

Email: gerbilsoft at gerbilsoft .com

**Comment by Masamune3210** [comment]
Will do tomorrow!

**Comment by Masamune3210** [comment]
Sent!

**Comment by GerbilSoft** [comment]
The DLC file is missing the strings entirely. I'm guessing it's referencing the strings from the original XEX, but we can't handle that case easily here.

**Comment by Masamune3210** [comment]
Ok, I started to wonder about that after you explained the same issue with GPD files
