### ISSUE TITLE
Tiger game.com ROMs with compressed icons aren't supported

### ISSUE THREAD

**Issue by simontime** [GerbilSoft/rom-properties#278]
Titles such as Tiger Web Link and game.com Internet use compressed icons which aren't supported, and decode to garbage.

I've been doing some reverse engineering of the game.com kernel recently, so here's a brief explanation of icon parsing (only the parts unimplemented in rom-properties):

[Gcom_RomHeader.unknown1](https://github.com/GerbilSoft/rom-properties/blob/master/src/libromdata/Handheld/gcom_structs.h#L46) is a set of flags used by the kernel for ROM header/icon handling.
- Bit 1 indicates if the game has an icon, if this isn't set, the kernel draws a black 64x64 bitmap.
- Bit 3 indicates whether RLE compression is used, and x, y in the ROM header becomes a big endian uint16_t specifying where the compressed data begins, relative to the physical address of the bank.

Some pseudocode to calculate the offset within the ROM:
```c
#define BANK_LEN       0x2000
#define BANK_LOAD_ADDR 0x6000

offset = ((hdr.icon.bank - 0x20) * BANK_LEN) + (((hdr.icon.x << 8) | hdr.icon.y) - BANK_LOAD_ADDR);
```
RLE decompression is performed like so (C reimplementation based on my disassembly):
```c
uint16_t decompress(uint8_t *in, uint8_t *out, uint16_t in_len)
{
    uint8_t *in_end, *out_start;
    uint16_t copy;
    
    in_end    = in + in_len;
    out_start = out;
    
    while (in < in_end)
    {
        copy = 0;
        
        if (*in == 0xc0) // 16-bit RLE
        {
            copy = (in[2] << 8) | in[1];
            memset(out, in[3], copy);
            in += 4;
        }
        else if (*in > 0xc0) // 8-bit RLE
        {
            copy = *in & 0x3f;
            memset(out, in[1], copy);
            in += 2;
        }
        else // raw copy
        {
            *out++ = *in++;
        }
        
        out += copy;
    }
    
    return out - out_start;
}
```
The icon is then rotated and flipped the same way as graphic banks are.

Hope this helps with its implementation!

**Comment by GerbilSoft** [comment]
I was wondering why Tiger Web Link's icon was showing up as garbage.

I'll take a look at implementing this tonight.
