### ISSUE TITLE
Feature Request: PS2 Boxart Support

### ISSUE THREAD

**Issue by Masamune3210** [GerbilSoft/rom-properties#284]
Would it be possible to add support for boxarts to PS2 ISO's? The Boot filename is usually if not completely the serial of the game which could be used to look up the box art at a website. Unless you have one better in mind, I found https://psxdatacenter.com/psx2/ which has lists and boxart to match the serial to

**Comment by GerbilSoft** [comment]
This was implemented in v2.2, though due to an oversight, some boxarts won't show up properly until I release v2.2.1. See: #386

**Comment by Masamune3210** [comment]
I had completely forgotten I made this request, if I had remembered I would have closed it when the release came out
