### ISSUE TITLE
[Feature Request] add cross-compilation support for Windows arm64

### ISSUE THREAD

**Issue by dennisameling** [GerbilSoft/rom-properties#287]
Thanks for this awesome shell extension! I use it to quickly check whether an executable is amd64/i386/arm64.

It works great on an amd64 device to check whether an executable is arm64, but I can't get it to work on an arm64 device. My Surface Pro X supports running i386 executables, but I think due to the shell integration we'll need a native DLL.

I just tried cross-compiling using `cmake .. -G "Visual Studio 16 2019" -A "arm64"`, but am running into the following error:

```
D:\repos\rom-properties\build>cmake --build . --config Release
Microsoft (R) Build Engine version 16.8.2+25e4d540b for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Generating libgnuintl_always_rebuild

  Generating libgnuintl_always_rebuild

  Generating libgnuintl_dll_command
  Error copying file (if different) from "D:/repos/rom-properties/extlib/gettext.win32/lib.arm64/libgnuintl-8.dll" to "D:/repos/rom-properties/build/bin/Release/libgnuintl-8.dll".
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(238,5): error MSB8066: Custom build for 'D:\repos\rom-properties\build\CMakeFiles\9491194fad6717ebf03226496e383687\libgnuintl_always_rebuild.rule; 
D:\repos\rom-properties\build\CMakeFiles\9491194fad6717ebf03226496e383687\libgnuintl_dll_command.rule;D:\repos\rom-properties\build\CMakeFiles\b8d84bc420154b246a3602a9ba01c278\libgnuintl_dll_target.rule' exited with code 1. [D:\repos\rom-properties\build\locale\ 
libgnuintl_dll_target.vcxproj]
```

So it looks like we'll need some prebuilt `gettext.win32/lib.arm64` DLLs. I'm happy to help with that, but could you give me a bit of guidance as to how you compiled it on Ubuntu, like you mentioned in https://github.com/GerbilSoft/rom-properties/commit/66276caba4adf847c6c8e4b5883d350480f15e48? I already have `mingw-w64` installed in my Ubuntu 20.04 instance. Thanks in advance 🚀

**Comment by GerbilSoft** [comment]
Specify `-DENABLE_NLS=OFF` and you should be able to build it without localization.

I'll need to provide precompiled arm64 gettext at some point.

**Comment by dennisameling** [comment]
Thanks, that helped!

When I first ran the build I got the following error:

```
D:\repos\rom-properties\extlib\rapidjson\include\rapidjson\rapidjson.h(244,1): fatal error C1189: #error:  Unknown machine endianess detected. User needs to define RAPIDJSON_ENDIAN. [D:\repos\rom-properties\build\src\librpbase\rpbase.vcxproj]
```

... so I added `#define RAPIDJSON_ENDIAN RAPIDJSON_LITTLEENDIAN` to `extlib\rapidjson\include\rapidjson\rapidjson.h` (from https://github.com/Tencent/rapidjson/issues/953) and it worked 🎉 

I uploaded the generated binaries here so others might benefit from it as well: https://github.com/dennisameling/rom-properties/releases/tag/v1.7.3-arm64

Shall I just leave this issue open for future reference?

**Comment by GerbilSoft** [comment]
I backported an upstream fix that detects MSVC/ARM64 correctly:
https://github.com/Tencent/rapidjson/commit/f91405801f88533c609d95f2fcc2d88811544d35
