### ISSUE TITLE
Add Pokemon Picross GBC title screen art

### ISSUE THREAD

**Issue by Masamune3210** [GerbilSoft/rom-properties#288]
If you let me know what settings and such are needed, I can grab a screenshot of the title for the recently discovered Pokemon Picross GBC game, if you want one. Currently no data is present other than the property sheet

**Comment by GerbilSoft** [comment]
Added a title screenshot for Pokémon Picross (AKVJ01) to RPDB. It should show up now, though you might need to delete the negative cache entry in `~/.cache/rom-properties` or `%USERPROFILE%\AppData\LocalLow\rom-properties`.

Also added symlinks for the Pokémon Gold and Silver 1999 Spaceworld prototypes. The title screens match the final, but the ROM header doesn't have a game ID.

Sidenote: Pokémon Picross's game ID is detected by the title screen code, but not by the regular field parser. Will look into this.
