### ISSUE TITLE
(Domestic and?) Export Title length too short to fit Mega Drive titles.

### ISSUE THREAD

**Issue by vaguerant** [GerbilSoft/rom-properties#29]
e.g. Check the following ROM (No-Intro naming): Great Circus Mystery Starring Mickey & Minnie, The (USA)

![nominnie](https://cloud.githubusercontent.com/assets/5259025/19640352/f0e9f4ae-9a27-11e6-9002-c11f0218f3a1.png)

The full export title of this game is `THE GREAT CIRCUS MYSTERY Starring Mickey&Minnie`.

**Comment by GerbilSoft** [comment]
The property sheet is a fixed size and can't easily be expanded. If I add vertical size, it'd bump off the Initial SP.

There might be another way to handle this. (Move vectors to a separate tab?)

**Comment by DankRank** [comment]
This should be fixed (at least on Windows) by 54bee06acd6be8a30fda540b230952fcbbb3d81f

**Comment by GerbilSoft** [comment]
Closed as per 54bee06acd6be8a30fda540b230952fcbbb3d81f.

GTK+ and Qt automatically resize the window, so it isn't a problem there.

I might consider using wordwrap and multiline later, but that will require a bit of reworking.
