### ISSUE TITLE
Kinect Rush A Disney Pixar Adventure [4D5309B6] not being parsed correctly

### ISSUE THREAD

**Issue by Masamune3210** [GerbilSoft/rom-properties#291]
This game for some reason checks out perfectly fine in agbx but doesn't show its icon or have any tabs other than the ISO-9660 tab. Let me know if you need any information or files. I'm getting a modded 360 soon so I can help out with other things should you need a modded 360 for anything

**Comment by Masamune3210** [comment]
[results.zip](https://github.com/GerbilSoft/rom-properties/files/6033515/results.zip)

**Comment by GerbilSoft** [comment]
Can you post the output from `rpcli`? I suspect that it might be a misdetection in the XGD3 heuristic.

**Comment by Masamune3210** [comment]
Reports a input/output error. The drive is fine, the other isos in the folder work in rpcli just fine, ill recheck in agbx to make sure nothing happened

**Comment by Masamune3210** [comment]
Nope, files fine. For some reason rpcli refuses to read it correctly. The shell extension at least sees it as a iso, because it has the raw disc info, but it seems to not be able to open the 360 part for some reason

**Comment by GerbilSoft** [comment]
That makes no sense, since if the CLI reports an I/O error, the shell extension should show the same problem.

Can you post a screenshot of the ISO-9660 tab?

**Comment by Masamune3210** [comment]
![image](https://user-images.githubusercontent.com/1053504/111055683-3a8ba080-843e-11eb-94b4-628e8abeb00e.png)
![image](https://user-images.githubusercontent.com/1053504/111055685-3eb7be00-843e-11eb-96d8-36ca17488268.png)

**Comment by Masamune3210** [comment]
This is the page for the second disc of the same game if it helps at all
![image](https://user-images.githubusercontent.com/1053504/111055689-4f683400-843e-11eb-8a8c-51cf9be259b1.png)

**Comment by GerbilSoft** [comment]
Can you post the first 64 KB of the disc image here? Specifically, I need to check the Primary Volume Descriptor.

**Comment by Masamune3210** [comment]
What would be the best way to do that, sorry

**Comment by GerbilSoft** [comment]
If you have access to a Linux system: `head --bytes=65536 disc.iso >disc64k.bin`
WSL and Cygwin might work for this as well, though it may have CRLF conversion issues.

Alternatively, some hex editors may be able to handle this without loading the entire ISO image into memory.

**Comment by Masamune3210** [comment]
[disc64k.zip](https://github.com/GerbilSoft/rom-properties/files/6136006/disc64k.zip)

**Comment by GerbilSoft** [comment]
The raw PVD creation timestamp is: `2011120716000000\xE0`

This *does* fit the heuristic used for XGD3, so there's something wrong elsewhere. Unfortunately I can't really debug this myself without having a full copy of the disc, so this will have to be on hold for now.

**Comment by Masamune3210** [comment]
I can upload and supply the file if needed

**Comment by GerbilSoft** [comment]
Send me an email with the relevant information and I'll take a look.

**Comment by Masamune3210** [comment]
Uploading now, will send the link when its done

**Comment by Masamune3210** [comment]
sent

**Comment by GerbilSoft** [comment]
Looks like this is a bit of an edge case.

The video partition's timestamp matches XGD2 Wave 14: 2011-12-07 16:00:00.00 -08:00
However, it's actually an XGD3 image, so the XDVDFS partition starts at the XGD3 offset, not XGD2.

Easiest thing to do here is to check for an XGD3 image if the XGD2 offset fails.
