### ISSUE TITLE
NBA 2K11 [5454087A] not showing icon and has error

### ISSUE THREAD

**Issue by Masamune3210** [GerbilSoft/rom-properties#292]
![image](https://user-images.githubusercontent.com/1053504/111055731-83dbf000-843e-11eb-84e6-eb74002eb413.png)

**Comment by Masamune3210** [comment]
Samurai Showdown Sen [534E07D5] has the same issue as well

**Comment by GerbilSoft** [comment]
Duplicate of #282. Please consolidate the two issues together by copying the info from here into #282.

**Comment by Masamune3210** [comment]
Ok, wasnt sure sorry
