### ISSUE TITLE
[Feature Request] Spanish translation

### ISSUE THREAD

**Issue by Amnesia1000** [GerbilSoft/rom-properties#293]
I am currently working on translating it, I open the Issue to share the es.po file when it is finished.

**Comment by GerbilSoft** [comment]
Please file a pull request when it's done. I'm not sure when I'm going to enforce "string freeze", but I want to get v1.8 out soon.

**Comment by Amnesia1000** [comment]
Ok

**Comment by Amnesia1000** [comment]
I have already finished the Spanish translation. But I'm not a programmer and I don't know how Github works. What should I do?

**Comment by GerbilSoft** [comment]
You can post the .po file here. I'd suggest looking up some git tutorials so you can create a pull request for updates later on.

**Comment by Amnesia1000** [comment]
[es.zip](https://github.com/GerbilSoft/rom-properties/files/6247524/es.zip)

I am going to find out about it. I also want to see once it is merged if everything is ok and fix anything that might have gone wrong.

**Comment by GerbilSoft** [comment]
A few minor issues with the .po file:
* It's encoded in UTF-16LE with a byte-order marker. It should be UTF-8 without a byte-order marker.
* It was based on an older version of rom-properties. I rebased it to the latest version.
* Some strings had the ending period outside of the double-quotes, which isn't valid syntax.

I fixed up and added es.po to the repository. Also note src/win32/res/rp-es_ES.rc, which contains the Win32 dialogs used in a Spanish locale. Win32 doesn't have layout auto-resizing, so we're using separate dialogs for each language, which requires translating the .rc files as well as the .po files. I copied most of the strings from the .po file that were also present in the KDE rp-config, but some strings still need to be translated.

On Linux, you should be able to compile and install and have the localizations show up properly. On Windows, the rp-config translation will work correctly, but you'll need to manually copy the `locale/es.gmo` file to `bin/Debug/locale/es/LC_MESSAGES/rom-properties.mo`.

**Comment by Amnesia1000** [comment]
Ok, great! Then I should translate from the .po file the new, and translate from the .rc file all the missing, right?

**Comment by GerbilSoft** [comment]
Initial localization committed in ef8b0b7cfaaf0a24c928569183eb3c2e96b84ff8.
