### ISSUE TITLE
Linux Manjaro KDE: Bad system call in rp-download sandbox

### ISSUE THREAD

**Issue by Amnesia1000** [GerbilSoft/rom-properties#294]
Linux Manjaro KDE

/usr/libexec/rp-download -v gba/title/E/ASOE78.png
URL: https://rpdb.gerbilsoft.com/gba/title/E/ASOE78.png
Cache Filename: /home/amnesia/.cache/rom-properties/gba/title/E/ASOE78.png
Llamada al sistema errónea

**Comment by GerbilSoft** [comment]
Looks like the rp-download sandbox broke again. Can you rebuild with debugging enabled, then rerun the `rp-download` command?

Add the following option to the CMake line: `-DCMAKE_BUILD_TYPE=Debug`

**Comment by Amnesia1000** [comment]
I just compiled again and tested the download and now the files are downloading fine.

**Comment by GerbilSoft** [comment]
That seems odd - enabling Debug shouldn't have fixed it; it should've printed the syscalls that were causing it to crash before.

**Comment by Amnesia1000** [comment]
I know, it may have been a network problem?

**Comment by GerbilSoft** [comment]
A network problem wouldn't have caused a "Bad system call" error. That's always an indication that something's wrong with the program, and it's usually that the syscall whitelist needs to be updated.

**Comment by Amnesia1000** [comment]
It is very strange, before opening the issue I deleted everything and reinstalled to make sure it was not a compilation problem.

But well... It was solved, thanks for the quick response.
