### ISSUE TITLE
Include support for Mega Drive ROMs with .md extension

### ISSUE THREAD

**Issue by vaguerant** [GerbilSoft/rom-properties#30]
Currently .md files aren't recognized as Mega Drive ROMs. This is the extension used by No-Intro's DATs, so it's reasonably common in the wild. The format is the same straight binary as .bin or .gen ROMs.

**Comment by GerbilSoft** [comment]
.md conflicts with Markdown, which is why it isn't currently enabled.

**Comment by GerbilSoft** [comment]
Closing this because it should be handled in issue #35, which is basically the same thing but for all systems that use "generic" extensions like .bin and .vb.
