### ISSUE TITLE
Properties window does not show thumbnails

### ISSUE THREAD

**Issue by Amnesia1000** [GerbilSoft/rom-properties#300]
The thumbnails of all roms are not displayed in the properties window.

Linux Manjaro KDE.
Roms that I have been able to test and do not show thumbnails: GBA, GB/GBC, WS/WSC, WII and NGP/NGPC

**Comment by GerbilSoft** [comment]
The properties window itself only displays an icon and/or banner if it's present. Other thumbnail types aren't displayed in the properties window.

**Comment by Amnesia1000** [comment]
Ok.

**Comment by GerbilSoft** [comment]
This was fixed by adding title screens using RPDB for the following systems:
* Game Boy (added in v1.6)
* Game Boy Advance (added in v1.6)
* Neo Geo Pocket (added in v1.8)
* WonderSwan (added in v1.8)

No title screens for Wii though, and it's unlikely I'll be adding that anytime soon.
