### ISSUE TITLE
Xbox 360 containers .fxs and .exs not showing metadata

### ISSUE THREAD

**Issue by 60fpshacksrock** [GerbilSoft/rom-properties#303]
I would like to report that .fxs and .exs Xbox 360 containers do not show metadata
when they are indeed container files. .fxs is for both Fallout games and .exs is for The Elder Scrolls V: Skyrim.

**Comment by GerbilSoft** [comment]
I found a sample Fallout save file online and it is in fact an Xbox 360 STFS container but with a different file extension. I'll add those two file extensions to the STFS parser.

**Comment by 60fpshacksrock** [comment]
Thank you for adding them, much appreciated.
I quite a lot use the PC versions of the games to mod my saves and then send them back to my 360.

Also, I'm not sure how it could be done or if you would consider it, but The Elder Scrolls IV: Oblivion
save container has no extension, but maybe it could be read as the header does contain the CON
text at the header.

Overall it's a great tool. Thank you much for sharing it.

**Comment by GerbilSoft** [comment]
I'm not sure if I can easily register a handler for files with no file extension. I'll need to check the MSDN documentation.

Sidenote: On most Linux desktop environments, if a file extension isn't recognized, the file is checked for a "magic number". STFS packages have one of the following magic numbers:
* `CON `: Console-specific, e.g. save files.
* `PIRS`: MS-signed for non-Xbox Live distribution.
* `LIVE`: MS-signed for Xbox Live distribution.

**Comment by 60fpshacksrock** [comment]
Not sure if it helps, but here is the naming scheme:
Save 2 - 01D3C7CEC00D16B0
The number increments with each save.
