### ISSUE TITLE
Latest MSVC 2019 runtime is incompatible with Windows XP

### ISSUE THREAD

**Issue by ccawley2011** [GerbilSoft/rom-properties#304]
If the MSVC 2015-2019 runtime is not installed, a link is provided to install the most recent version. However, while the latest version installs without issue, applications using it won't work due to missing imports required by `MSVCP140.DLL`. Using the [MSVC 2017](https://visualstudio.microsoft.com/vs/older-downloads/#microsoft-visual-c-redistributable-for-visual-studio-2017) runtime works fine with rom-properties on Windows XP, so it would be useful to link to that when the installer is run on Windows XP.

**Comment by GerbilSoft** [comment]
Looks like all of the missing imports are related to thread handling, and they were added in Windows Vista.
