### ISSUE TITLE
Incorrect DS regions

### ISSUE THREAD

**Issue by Amnesia1000** [GerbilSoft/rom-properties#308]
A problem similar to those of Wii/Gamecube. Some 3DS covers of a specific language and region are located in the gametdb folder of another region, for example, "Pokemon - White Edition 2 (Spain)", of Spanish language and Spanish region and ID IRDS01, is not in the "ES" folder, but in the "EN" folder (in gametdb). In the rom-properties cache folder, a 0-byte image with that ID is created in the "ES" folder.

**Comment by GerbilSoft** [comment]
Solution is to add "EN" fallback to various PAL regions. Will do this later today.

**Comment by Amnesia1000** [comment]
Works perfectly
