### ISSUE TITLE
Unable to delete iso files

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [GerbilSoft/rom-properties#311]
When you have this installed and try to delete an iso file (in my case it is an unbuntu installer and an windows installer), the explorer claims it cannot be deleted as it is in use by windows explorer. Only way out is to kill explorer.exe and then delete via cmd/powershell

Screenshot (german):
![image](https://user-images.githubusercontent.com/27149563/120278471-9c2d0f80-c2b5-11eb-9ac9-0c17cb672324.png)

**Comment by DankRank** [comment]
Make sure you have the lastest version of rom-properties, because this bug existed in 1.6 and was fixed in 1.7 (see #249)

**Comment by ErdbeerbaerLP** [comment]
Oh, for some reason, it didn't update it when I uninstalled it, unzipped and re-installed it.
I can delete them again :)
