### ISSUE TITLE
tinyxml2.dll isn't packaged correctly

### ISSUE THREAD

**Issue by ccawley2011** [GerbilSoft/rom-properties#313]
In the 1.8 release archive, the 32-bit version of `tinyxml2.dll` is installed in a "bin" subdirectory, while the 64-bit version is missing. This leads to a crash when attempting to open Windows executables.

**Comment by GerbilSoft** [comment]
I thought I fixed this before. Besides that, it shouldn't outright crash, since it's supposed to be using delay-load, so that's two bugs to fix:

1. Figure out why it's not using delay-load for TinyXML2.
2. Fix packaging.
