### ISSUE TITLE
[Issue] ROM Properties Install Causing Certain Icons To Disappear

### ISSUE THREAD

**Issue by JazzMartian** [GerbilSoft/rom-properties#318]
After I install ROM Properties the icons for certain associated programs fail to show. 7zip and Notepad++ associated file icons stop showing, for one example. I've tried uninstalling, at which point the icons for 7zip and Notepad++ file types will show again, but when I reinstall ROM Properties, they again, fail to display. I'm running the latest build of Windows 10.

**Comment by Masamune3210** [comment]
what file types, do the icons fail in totality or are they replaced with something else

**Comment by GerbilSoft** [comment]
See issue #318 for more information.

Test build: https://ci.appveyor.com/project/GerbilSoft/rom-properties/builds/40630143
Can you try this and see if it has the same issue?

NOTE: You may have to run `regsvr32 /u rom-properties.dll` on the old version at least twice before registering the new version.

**Comment by JazzMartian** [comment]
> 
> 
> what file types, do the icons fail in totality or are they replaced with something else

Any file type that's associated with 7zip (.7z, .rar, .zip, etc.) and Notepad++ (.txt, .md, .cfg, etc.). If I make 7zip the default program to open any type of archive, the icon in Windows Explorer is blank. The same goes for Notepad++.

**Comment by JazzMartian** [comment]
> 
> 
> See issue #318 for more information.
> 
> Test build: https://ci.appveyor.com/project/GerbilSoft/rom-properties/builds/40630143
> Can you try this and see if it has the same issue?
> 
> NOTE: You may have to run `regsvr32 /u rom-properties.dll` on the old version at least twice before registering the new version.

Sorry for the late reply. Anyways, I'd be glad to test that build, but I'm having trouble figuring out how to download it from that link.

**Comment by GerbilSoft** [comment]
Here's the most recent build: (64-bit release build, MSVC 2015)
https://ci.appveyor.com/project/GerbilSoft/rom-properties/builds/40732653
https://ci.appveyor.com/api/buildjobs/k2ra6pn1x416a7ka/artifacts/rom-properties_1.8.3%2B-win64.zip

**Comment by JazzMartian** [comment]
> 
> 
> Here's the most recent build: (64-bit release build, MSVC 2015)
> https://ci.appveyor.com/project/GerbilSoft/rom-properties/builds/40732653
> https://ci.appveyor.com/api/buildjobs/k2ra6pn1x416a7ka/artifacts/rom-properties_1.8.3%2B-win64.zip

I have no idea of how to download a working installer from the first link, and the second link contains other files but not an installer.

**Comment by Masamune3210** [comment]
Right click the second link and hit save as, and it should let you save it as a zip. 

If that doesn't work the first link, click Environment x64.....Release, and then Artifacts, and then it should let you download the zip

**Comment by JazzMartian** [comment]
> 
> 
> Right click the second link and hit save as, and it should let you save it as a zip.
> 
> If that doesn't work the first link, click Environment x64.....Release, and then Artifacts, and then it should let you download the zip

Thanks for your help. I was always able to download from the second link. The problem is that there's no installer in the archive. It's the same thing with the archive in the first link.

**Comment by Masamune3210** [comment]
There wont be a installer as they are only made for release builds. You have to manually move the files to a safe place where you want them to stay, and run "regsvr32 *path to amd64\rom-properties.dll* in a administrator command prompt or powershell window

**Comment by JazzMartian** [comment]
> 
> 
> There wont be a installer as they are only made for release builds. You have to manually move the files to a safe place where you want them to stay, and run "regsvr32 _path to amd64\rom-properties.dll_ in a administrator command prompt or powershell window

Ok thank you. After registering this version of ROM Properties, 7zip and Notepad++ associated file icons are now displaying in Windows Explorer.

**Comment by GerbilSoft** [comment]
Closing as fixed for 1.9.
