### ISSUE TITLE
[Feature Request] Add support for Windows 11 in compatibility check

### ISSUE THREAD

**Issue by Masamune3210** [GerbilSoft/rom-properties#320]
Since Windows 11 comes out in roughly a week, any plans to update the compat check in exe properties and related to show support for Windows 11 supported exe?

**Comment by GerbilSoft** [comment]
From what I can tell, Microsoft isn't adding a new supportedOS GUID value for Windows 11; they're keeping it the same as Windows 10.

https://docs.microsoft.com/en-us/windows/win32/sysinfo/targeting-your-application-at-windows-8-1
https://stackoverflow.com/questions/68240304/whats-the-supportedos-guid-for-windows-11
