### ISSUE TITLE
[Feature Request] Add Support OpenBOR .PAK Files 

### ISSUE THREAD

**Issue by JazzMartian** [GerbilSoft/rom-properties#327]
Title screen images and relevant information for the ROMs would be an amazing addition to the extension. I would be willing to contribute in anyway I can, like providing images and developer names.

**Comment by JazzMartian** [comment]
Due to how 'ROM Properties' works, this isn't a realistic request, as OpenBOR .paks aren't cataloged in any known database (with checksum values). So I'm closing this request.

**Comment by GerbilSoft** [comment]
Do the .pak files not have any sort of useful metadata included?

**Comment by JazzMartian** [comment]
> Do the .pak files not have any sort of useful metadata included?

I looked into it, and I couldn't find any with any of the programs I checked with. Thanks for asking further into it though.
