### ISSUE TITLE
[Feature Request] Early New Executable file timestamps

### ISSUE THREAD

**Issue by starfrost013** [GerbilSoft/rom-properties#329]
Very early New Executables (probably using linker version 4.0, found in Windows 1.0 Alpha, Beta, PE, maybe 1.xx and also the final release?) had a DOS-style date timestamp in lieu of a CRC at the 8th byte of the NE header. These files can be determined by having a "nonsense" checksum and potentially other differences (?).

It would be nice for my specific research to be able to view these early checksums with a "single click".

[EarlyNE.zip](https://github.com/GerbilSoft/rom-properties/files/8092898/EarlyNE.zip)

**Comment by GerbilSoft** [comment]
Added decoding for the timestamp. If the resulting timestamp appears valid and is in between 1983-1985, it will be displayed.
