### ISSUE TITLE
Compat with GTK4 and Nautilus 4.x

### ISSUE THREAD

**Issue by Amnesia1000** [GerbilSoft/rom-properties#332]
Currently I have been using Manjaro Gnome based on GTK4 and Gnome apps 4.x and rom properties does not show thumbnails of any system.

**Comment by GerbilSoft** [comment]
There's preliminary support for GTK4, but it's experimental because I haven't been able to test it yet. I'll see if I can build Nautilus 42 later.

**Comment by Amnesia1000** [comment]
Excellent

**Comment by Amnesia1000** [comment]
The problem with gnome was fixed? I think it was a problem with bubblewrap. I've been using gnome for a long time and I don't know if it's the same problem or just incompatibility with gnome 4 and gtk4

**Comment by Amnesia1000** [comment]
Also, rp-config doesn't start with GTK, but it doesn't have a problem with QT, shouldn't it open anyway?

This is the error I get when I try to open it
"*** ERROR: Could not find rp_show_config_dialog() in any installed rom-properties plugin."

**Comment by GerbilSoft** [comment]
I haven't yet written a GTK+ version of rp-config, so it won't work if the KDE4 or KF5 plugins aren't installed.

**Comment by Amnesia1000** [comment]
Forgive my ignorance, but QT applications are possible to start in a GTK environment, what would be the difference with these? Is it possible to install some library to be able to open the RP configuration?

**Comment by Amnesia1000** [comment]
I just did a clean install of Manjaro with Gnome 4.2 and nautilus shows the RP tab, but it doesn't show any thumbnails. 
Also I saw in 1.8.3 that there is experimental support for GTK4, how can I test it? Is there any command I should add to cmake to enable it?

Also, speaking of another topic, you are right, when installing Kio (I think) it opened without any problem rp-config.

**Comment by GerbilSoft** [comment]
Nautilus 43 was released this week, and it was ported to GTK4. Unfortunately, it seems they changed the property page API to only accept key/value pairs instead of arbitrary GtkWidgets, which means it won't be possible to make a full port of the property page. I might be able to do a reduced version that excludes icons and lists.

**Comment by Amnesia1000** [comment]
Hopefully soon we will have rom properties in the new nautilus

**Comment by GerbilSoft** [comment]
Comparison of Thunar (GTK3) and Nautilus 43 (GTK4):

Thunar (GTK3):
![Thunar (GTK3) version showing Sonic Colors (DS)](https://user-images.githubusercontent.com/6764716/193434222-2d96e30e-226b-411f-bf3a-d3f0be255cda.png)

Nautilus 43 (GTK4):
![Nautilus 43 (GTK4) version showing Sonic Colors (DS)](https://user-images.githubusercontent.com/6764716/193434231-9522e913-0111-4103-bc85-0cfb60635022.png)
