### ISSUE TITLE
Wii WAD files are not showing internal icon or banner no matter the priority

### ISSUE THREAD

**Issue by Masamune3210** [GerbilSoft/rom-properties#335]
No matter what I change in the priorities or how many times I clean the icon caches, I cannot for the life of me get any WAD's to show the internal icon or banner. All keys except for rvt-korean and rvt-debug are filled and valid, but disabling everything except for internal icon/banner just leaves the standard file icon from Windows instead of anything from the shell extension

**Comment by Masamune3210** [comment]
This is on latest release, sorry for not putting it in the first post

**Comment by GerbilSoft** [comment]
Standard channel WADs don't have an internal icon or banner that can be parsed by rom-properties. They use an animated Wii banner instead of a static image.

Only DLC WADs and save file backups have a static icon/banner that can be displayed by the WAD parser.

What WAD file are you testing here?

**Comment by Masamune3210** [comment]
Likely was testing a channel like you assumed, I'll keep the limitation in mind
