### ISSUE TITLE
aligned_uptr<>::get() trips -Werror=nonnull

### ISSUE THREAD

**Issue by Amnesia1000** [GerbilSoft/rom-properties#336]
When I want to compile rp, I get error:

`[ 40%] Building CXX object src/libromdata/CMakeFiles/romdata.dir/Console/WiiWIBN.cpp.o
/home/ale/.comp/rom-properties/src/libromdata/Console/WiiWIBN.cpp: En la función miembro ‘const LibRpTexture::rp_image* LibRomData::WiiWIBNPrivate::loadIcon()’:
/home/ale/.comp/rom-properties/src/libromdata/Console/WiiWIBN.cpp:133:40: error: argument 3 is null but the corresponding size argument 4 value is 36864 [-Werror=nonnull]
  133 |         size_t size = file->seekAndRead(iconstartaddr, icondata.get(), iconsizetotal);
      |                       ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
En el fichero incluido desde /home/ale/.comp/rom-properties/src/libromdata/../librpbase/disc/PartitionFile.hpp:12,
                 desde /home/ale/.comp/rom-properties/src/libromdata/stdafx.h:79,
                 desde /home/ale/.comp/rom-properties/src/libromdata/Console/WiiWIBN.cpp:9:
/home/ale/.comp/rom-properties/src/libromdata/../librpfile/IRpFile.hpp:234:31: nota: in a call to function ‘size_t LibRpFile::IRpFile::seekAndRead(off64_t, void*, size_t)’ declared with attribute ‘access (write_only, 3, 4)’
  234 |                 inline size_t seekAndRead(off64_t pos, void *ptr, size_t size)
      |                               ^~~~~~~~~~~
cc1plus: algunos avisos se tratan como errores
make[2]: *** [src/libromdata/CMakeFiles/romdata.dir/build.make:426: src/libromdata/CMakeFiles/romdata.dir/Console/WiiWIBN.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1626: src/libromdata/CMakeFiles/romdata.dir/all] Error 2
make: *** [Makefile:166: all] Error 2`

Apparently related to Wii

**Comment by GerbilSoft** [comment]
I can't seem to reproduce this here. What compiler are you using, and what version?

The relevant code:

```
auto icondata = aligned_uptr<uint8_t>(16, iconsizetotal);
size_t size = file->seekAndRead(iconstartaddr, icondata.get(), iconsizetotal);
```

seekAndRead() is annotated to indicate that argument 2 is a buffer pointer and argument 3 is the size of the buffer, but icondata.get() should always be non-NULL.

**Comment by GerbilSoft** [comment]
I hit this issue when running a Coverity build. I added a workaround for now.

**Comment by Amnesia1000** [comment]
So Fast
