### ISSUE TITLE
COM/NE hybrid file not detected as either by rom-properties [Multitasking MSDOS 4.00 IBMDOS.COM]

### ISSUE THREAD

**Issue by starfrost013** [GerbilSoft/rom-properties#337]
Multitasking MS-DOS 4.00 (also known as European DOS 4.0, "internal revision 6.7 85/11/26")'s IBMDOS.COM is a COM/NE hybrid file. It has no MZ header, but there is an NE header and a valid NE binary starting at 0x1190. The binary can be hacked into being detected by ROM-Properties by inserting a valid MZ header with an e_lfanew value of 0x1190. (interestingly, it will not load properly (only exports shown) in IDA Pro 7.0 if the file is not padded with 0x200 0x00 bytes before the start of the file, due to a bug in NE header).

ibmdos.com is the original file, whereas ibmdos_ne.exe is the file patched to work in ROM-Properties and IDA.
[IBMDOS.zip](https://github.com/GerbilSoft/rom-properties/files/8765773/IBMDOS.zip)

**Comment by GerbilSoft** [comment]
The `file` command identifies this as a DOS COM executable by the x86 jump instruction in the header. I don't see anything referencing the NE header at 0x1190, though.

Is the NE header always at 0x1190 in a hybrid COM/NE executable, or is there a field that I'm missing here? Alternatively, is this just a unique thing in IBMDOS.COM that isn't used in any other program?

**Comment by GerbilSoft** [comment]
Added this in with a hard-coded 0x1190 offset for now.

**Comment by starfrost013** [comment]
This is a unique case as far as I am aware - I do not know of any other COM/NE hybrids (only EXE/NE ones). Possibly in OS/2.

MDOS4 is a very unique operating system. It was likely used as the base code for OS/2 from my research. The code is very different to MS-DOS 3.1 (although it began development long before MS-DOS 3.1 or 3.0, around late 1982) because it was largely rewritten in C, for a start, and it has a "newer" exports-based API as well as legacy int 21h. The NE format was invented for this OS, and there were plans to integrate it with early Windows - although WIndows 1.01 doesn't even run on MDOS 4, even though it has code specifically for it. However it never panned out because nobody really saw the use case for a real-mode multitasking OS (apps had to be custom written and as far as I know no MDOS4 apps were ever made). 

Overall, it's possible this format was only used for one file in this one very specific OS. There was an MDOS 4.1 (ICL OEM only) released in 1987, but no copy of it exists online. (There are several copies of MDOS4 online, and one of them has the string "internal revision 6.7, 85/11/26" hexedited to not display, as if it was some kind of beta release quickly patched to look more final...)
