### ISSUE TITLE
Inaccurate OS Version display for Nintendo 64 ROMs

### ISSUE THREAD

**Issue by ghost** [GerbilSoft/rom-properties#339]
Currently, rom-properties displays the OS version field like so:  `OS {os_version[2]}{os_version[3]}`.

However, the proper way to display this field appears to be like so: `OS{os_version[2] / 10}.{os_version[2] % 10}{os_version[3]}`.

Doing so for a game like `Dr. Mario 64` results in `OS2.0K`, which can be searched using Google to find official Nintendo 64 SDK documentation referencing that exact formatting for the OS version, proving that its correct.

**Comment by GerbilSoft** [comment]
Fixed; it now shows values similar to "OS 2.0K".

**Comment by GerbilSoft** [comment]
...and now it shows "OS2.0K", without the space.
