### ISSUE TITLE
IExtractIcon: Windows XP doesn't like non-square icons.

### ISSUE THREAD

**Issue by GerbilSoft** [GerbilSoft/rom-properties#34]
Windows will automatically stretch non-square icons to make them square, which makes them have a screwy aspect ratio. This isn't noticeable in the `master` branch right now, but the new amiibo code downloads thumbnails from http://amiibo.life/, and these thumbnails aren't necessarily square.

Standard thumbnails (IExtractImage) do render with the correct aspect ratio.

Need to test this on Windows 7.

**Comment by cheatfreak47** [comment]
Bleep Bloop:

Occasionally on Windows 10 Pro at least I've noticed that icons aren't properly centered or aspect corrected for unknown reasons.

**Comment by cheatfreak47** [comment]
Since 1.0 is a major release I'd like to pitch my two cents that this might be best suited for 1.0, rather than 1.1- windows behaves very strangely with the non-square icons sometimes.

**Comment by GerbilSoft** [comment]
Changed to 1.0. The feature/config-dialog branch reworks RP_ExtractIcons a bit so they use TCreateThumbnail like all the other classes, so this may be easier to do now.
