### ISSUE TITLE
Doesn't show properties for Nintendo 64 ROMs with different Clock Rate

### ISSUE THREAD

**Issue by ghost** [GerbilSoft/rom-properties#340]
Since rom-properties checks the first 8 bytes of a ROM to get the byte order, it ends up not detecting certain ROMs with a clock rate that is not 0xF.

Two examples of this are Cruis'n USA and Star Fox 64. Cruis'n USA has the clock rate as 0x3B9ACAF (60.85MHz), while Star Fox 64 has it as 0x3A07F5F (62.5MHz, the default).

The check should be changed to only cover the first 4 bytes (the PI_BSD_DOM1 configuration data) so that these ROMs are properly supported. Those values should be the same for every single Nintendo 64 ROM.

**Comment by GerbilSoft** [comment]
In addition to fixing this, the Clock Rate field is now displayed if it's non-zero. (If 0, it's shown as "default".)

**Comment by GerbilSoft** [comment]
Quick update: I changed the way the frequencies were formatted, so I checked the files again to make sure it didn't break. Star Fox is showing 60.850 MHz, and Cruis'n USA is showing 62.500 MHz; I think you had it swapped in your original post. (The hex values are correct, though.)

**Comment by ghost** [comment]
Sorry for taking a while to reply back, only noticed that you replied again while randomly checking my emails.

You are correct, I did have the clock rates swapped. By the time I realized, it had already been fixed/implemented into rom-properties and thus I didn't see it as necessary to edit the original message.

The formatting I used (60.85, 62.5) was found in official documentation for the makerom tool (http://ultra64.ca/files/documentation/online-manuals/functions_reference_manual_2.0i/tools/makerom.html), so that would be the "official" formatting, though it doesn't really matter.
