### ISSUE TITLE
Add an dll import/export function tab?

### ISSUE THREAD

**Issue by vaualbus** [GerbilSoft/rom-properties#348]
It would be cool for developers to add a tab that has the dll exports and imports in there.

**Comment by GerbilSoft** [comment]
Sounds like a useful feature. I'm not sure if I should handle undecorating C++ symbols though, and if I do that, there's a bunch of formats. (gcc, MSVC, different versions...)

Would also be a good idea to add that to ELF as well.

**Comment by DankRank** [comment]
This would be an extremely useful feature. Total Commander has a plugin called [PEViewer](https://totalcmd.net/plugring/peviewer.html) and I use it all the time to figure out dependencies and used APIs of modules. Here's how it looks:
![](http://wincmd.ru/files/wlx_peviewer.png)
There are two UI ideas in here that would be nice to have (but I'm not sure they're worth the effort):
- The imports are grouped by DLL. The list only shows imports from the currently selected DLLs.
- The symbol decoration can be toggled by right-clicking any of the lists and selecting "Undecorate C++ Names" option.

To undecorate MSVC symbols on Windows, there's [UnDecorateSymbolName](https://docs.microsoft.com/en-us/windows/win32/api/dbghelp/nf-dbghelp-undecoratesymbolname) in imagehlp.dll. This is a good reference for rolling our own: https://www.agner.org/optimize/calling_conventions.pdf (chapter 8)

**Comment by GerbilSoft** [comment]
Merged, and slightly improved by adding sorting in the imports tab. Also fixed an issue where exports/imports didn't show up if the executable has no resources.

It would be nice to add NE exports/imports, but that isn't as useful nowadays. I might take a look at it later.
