### ISSUE TITLE
rpcli: bad table alignment on multibyte characters

### ISSUE THREAD

**Issue by DankRank** [GerbilSoft/rom-properties#353]
As can be seen with © and ®:
```
StringFileInfo:  |      Key       |                    Value                     |
                 |----------------|----------------------------------------------|
                 |CompanyName     |Microsoft Corporation                         |
                 |FileDescription |ApiSet Stub DLL                               |
                 |FileVersion     |10.0.10240.16384 (th1.150709-1700)            |
                 |InternalName    |apisetstub                                    |
                 |LegalCopyright  |© Microsoft Corporation. All rights reserved.|
                 |OriginalFilename|apisetstub                                    |
                 |ProductName     |Microsoft® Windows® Operating System        |
                 |ProductVersion  |10.0.10240.16384                              |
```
Proper alignment will probably also require taking wide (e.g. Japanese) characters into consideration.

**Comment by GerbilSoft** [comment]
Fixing this would require two things:
1. Using a UTF-8 aware strlen(). I could probably write my own, though it would be less efficient than those available elsewhere. (mbslen() depends on the system locale, and I'd rather not depend on it.)
2. Some way to identify full-width characters and accommodate for that.
3. On Windows, the ANSI functions are ANSI, unless a particular manifest entry is added for Windows 10 1903 to allow using UTF-8 as the "ANSI" codepage.

I'll probably do both of these.

**Comment by DankRank** [comment]
Here's how to make it work once you have those things:
We need a way to count utf-8 codepoints (`u8len`), and the count of full-width characters (`fwlen`)
To calculate column width `colSize`, for each string s, do `u8len(s) + fwlen(s)` and take the maximum.
The actual value passed to std::setw for a given string s should be `colSize + (strlen(s) - u8len(s)) - fwlen(s)`

The `strlen(s) - u8len(s)` in the above expression represents the number of utf-8 continuation bytes. They contribute 0 width to the screen output, but are still counted by setw (which operates on bytes), so we must expand the column by that amount to compensate for it. Similarly, we subtract `fwlen(s)` to compensate for fw codepoints taking 2 width but being counted as 1.
As a sanity check, consider the setw value for the longest string in the list (the one that defines `colSize`). When you plug the expression for colSize into it, it cancels to just `strlen(s)`, which is exactly what's needed to output s without any padding.

**Comment by DankRank** [comment]
Actually, we don't need an efficient `u8len`. We're going to have to decode the individual codepoints for fwlen anyway, so we might as well calculate `u8len(s) + fwlen(s)` at that point. Let's call that sum `visual_width(s)`.
This makes colSize equal to `visual_width(s)`, and setw width equal to `colSize + strlen(s) - visual_width(s)`.

There happens to be a function in POSIX called [wcswidth](https://man7.org/linux/man-pages/man3/wcswidth.3.html) which does exactly what we need, though it operates on wchars. I found this permissively-licensed implementation: https://www.cl.cam.ac.uk/~mgk25/ucs/wcwidth.c

**Comment by GerbilSoft** [comment]
I decided to write my own UTF-8 strlen() for use in TextOut_text.cpp. It parses UTF-8 sequences and determines the actual codepoint, then uses wcwidth() to get the character width. On Windows, I'll use a bundled copy of gnulib's uc_width() function.

**Comment by GerbilSoft** [comment]
For the record, I checked the u8_width() function, and it requires a string length in code points, which doesn't work with the multi-line string code (counts in bytes). So I'm sticking with the utf8_disp_strlen() function I wrote in TextFuncs_strlen.cpp, which uses wcwidth() (or uc_width() when using the gnulib version).
