### ISSUE TITLE
Crash in rp-config on Windows XP

### ISSUE THREAD

**Issue by ccawley2011** [GerbilSoft/rom-properties#361]
This occurs when attempting to view the Options or Achivements tabs. The error signature points towards zlib1.dll, which suggests that it's crashing when attempting to read the language and achievement images.

**Comment by GerbilSoft** [comment]
I'm not able to reproduce this crash on my Windows XP VM using rom-properties 2.0.

If possible, can you custom-compile a build using MSVC 2017 or 2019 on a newer Windows system (use the vc141_xp toolset), then use the MSVC Remote Debugger to get a stacktrace?

EDIT: Deleting i386/zlib1.dll results in icons disappearing in both tabs, but it still isn't crashing here.

**Comment by ccawley2011** [comment]
I've figured out why it's crashing - zlib-ng is attempting to use AVX2 optimized routines without checking that the OS supports the YMM registers. I'll look into creating a pull request for this in zlib-ng.

**Comment by GerbilSoft** [comment]
That explains why it's not crashing for me. I'm using an Intel Ivy Bridge CPU, which doesn't have AVX2. It's only checking for AVX2 support in the CPU, not the OS.

**Comment by ccawley2011** [comment]
I've opened zlib-ng/zlib-ng#1351 which works correctly with the test programs. I've also backported the changes to v2.0.6 in #362, and I can confirm that fixes rom-properties.
