### ISSUE TITLE
"rp-config.desktop" file error

### ISSUE THREAD

**Issue by Amnesia1000** [GerbilSoft/rom-properties#367]
When installing rom-properties, the rp-config desktop file is installed in the path "/usr/share/applications/com.gerbilsoft.rom-properties.rp-config.desktop/", and this makes that in gnome the icon is not shown because it is inside a folder. I don't really know if it doesn't show the icon because it is inside a folder, but when I change the file to the "applications" folder the icon is shown without any problem.

**Comment by GerbilSoft** [comment]
Fixed by using INSTALL()'s RENAME parameter to rename the file instead of specifying the new filename in the destination path.

**Comment by Amnesia1000** [comment]
Excelent

**Comment by Amnesia1000** [comment]
@GerbilSoft I just updated rom-properties, but the desktop file does not install, because it finds a folder with the same name (I guess), I do not know if this is possible, but when installing could the script check if the folder exists, and if so delete it and then install the desktop file.

Or inform that to install version 2.x the previous version must be uninstalled first to resolve this conflict.

**Comment by GerbilSoft** [comment]
I don't think CMake's installation functionality supports doing that. I can add a note that it needs to be removed manually.

Packaged versions won't have this problem because the package manager will remove all old files and directories before installing new ones.

**Comment by Amnesia1000** [comment]
Ok.
