### ISSUE TITLE
rp-config does not save configuration and keys in Manjaro Gnome.

### ISSUE THREAD

**Issue by Amnesia1000** [GerbilSoft/rom-properties#368]
rp-config does not save settings and keys in Manjaro Gnome (keys.conf and rom-properties.conf files are not created).
Manually creating keys.conf and rom-properties.conf files shows the settings and keys, but any changes you make are not saved.

**Comment by GerbilSoft** [comment]
It seems that the GTK rp-config frontend doesn't create rom-properties.conf if it doesn't exist already. Making a change if the file already exists does seem to save settings for me, though.

**Comment by Amnesia1000** [comment]
Excellent, I can't test it at the moment, but as soon as I can I will comment if it is fixed. WHAT SPEED
