### ISSUE TITLE
rp-config does not save settings and keys in Manjaro Gnome

### ISSUE THREAD

**Issue by Amnesia1000** [GerbilSoft/rom-properties#369]
rp-config does not save settings and keys in Manjaro Gnome (keys.conf and rom-properties.conf files are not created).
Manually creating keys.conf and rom-properties.conf files shows the settings and keys, but any changes you make are not saved.

**Comment by GerbilSoft** [comment]
Duplicate of #368.

**Comment by Amnesia1000** [comment]
The two issues were closed
