### ISSUE TITLE
Amiibos without thumbnails (Gnome)

### ISSUE THREAD

**Issue by Amnesia1000** [GerbilSoft/rom-properties#370]
Currently as gnome does not support covers, I have installed rom-properties on windows and copied all the downloaded thumbnails to Manjaro Gnome. All thumbnails are displayed without any problem, except for the amiibo files.
It should be noted that in windows it displays them without any problem.
I have made sure that the amiibos are good dumps, and that the IDs correspond with the images.

amiibo folder image
![Captura desde 2022-10-24 15-01-25](https://user-images.githubusercontent.com/45115804/197594481-4e9b283a-e62f-4d17-bd5b-36e031833c52.png)
GameCube folder image
![Captura desde 2022-10-24 15-01-42](https://user-images.githubusercontent.com/45115804/197594540-26fe81d0-e8ce-4c3c-b7ae-a6f56c3067d0.png)

**Comment by GerbilSoft** [comment]
It's likely an issue with ".bin" being too generic, so GNOME isn't able to detect the MIME type properly.

Does it work if renamed to ".nfp"?

**Comment by Amnesia1000** [comment]
Yes, it works, so there is no way to fix it, is it a gnome "problem"?

**Comment by GerbilSoft** [comment]
I might be able to add extra MIME data to have it detect the file properly, but I don't want to add the ".bin" extension because that'll cause misdetections.

**Comment by Amnesia1000** [comment]
Ok, thanks

**Comment by GerbilSoft** [comment]
Added magic number values to the rom-properties.xml MIME database file. That seems to fix it here.
