### ISSUE TITLE
PlayStation 1 and 2 covers

### ISSUE THREAD

**Issue by DankRank** [GerbilSoft/rom-properties#371]
Finally someone collected the covers and named them according to the serial (unlike thumbnails.libretro.com) and downscaled them to a reasonable size (unlike psxdatacenter.com). The size is 500x500 for PS1 and 512x736 for PS2, but there are some outliers.

URLs:
`https://raw.githubusercontent.com/xlenore/psx-covers/main/covers/${serial}.jpg`
`https://raw.githubusercontent.com/xlenore/ps2-covers/main/covers/${serial}.jpg`

Source:
https://github.com/xlenore/psx-covers
https://github.com/xlenore/ps2-covers

Total size: 
```
493M    psx-covers/covers
1.1G    ps2-covers/covers
```

As a prerequisite we need to extract the correctly formatted serial (`SLUS-12345`) from the boot filename (typically `SLUS_123.45`), and handle all the edge cases involved in doing that. See this script for reference.
https://gist.github.com/i30817/96674a3de8d9e4cb890e92cec3f36990

**Comment by GerbilSoft** [comment]
This looks good. I'll probably mirror the repository to rpdb to avoid having a dependency on GitHub, but will definitely mention the repositories in the README files.

**Comment by GerbilSoft** [comment]
Need to increase the size of the rp-config dialogs on Windows, will get to that later.
