### ISSUE TITLE
Ratio of ps2 longbox thumbnails looks wrong?

### ISSUE THREAD

**Issue by Masamune3210** [GerbilSoft/rom-properties#385]
I would look myself to see what they are getting displayed as, but to my eye, the ps2 thumbnails look to have the wrong aspect ratio. It looks like they are taller and not as wide as they should be

![image](https://github.com/GerbilSoft/rom-properties/assets/1053504/9b307cbb-9802-4109-83ef-f42926bca322)

**Comment by GerbilSoft** [comment]
The original file has a correct aspect ratio: http://rpdb.gerbilsoft.com/ps2/cover/SLES/SLES-55103.jpg

This is definitely a Windows rendering issue. I'll need to figure out why it's being rendered incorrectly.

**Comment by GerbilSoft** [comment]
This is also affecting Wii U boxart, and probably others. (Tested on Windows 7.)

It *should* be creating a squared thumbnail, but obviously something is wrong...

**Comment by Masamune3210** [comment]
Watch, it's going to be something stupid like Windows changing how thumbnails work.... again

**Comment by GerbilSoft** [comment]
It seems the "squaring" function that's needed for icons to work properly somehow caused long boxes to get squished. I'm pretty sure it worked before...

Disabled squaring on everything except icons and it seems to work now. Tested on Windows 7 with IThumbnailProvider. Will test IExtractImage later to ensure it isn't broken, but IExtractImage is generally only used on Windows XP and other older software.

**Comment by Masamune3210** [comment]
As soon as the build pops out of appveyor I will test on my end to make sure everything is good

**Comment by Masamune3210** [comment]
@GerbilSoft Aspect Ratio is still wrong
![image](https://github.com/GerbilSoft/rom-properties/assets/1053504/d3043acd-3dba-4e50-8713-f29a683c3307)
![image](https://github.com/GerbilSoft/rom-properties/assets/1053504/7f2b6420-7bc0-45ab-a0a5-060734682571)

**Comment by GerbilSoft** [comment]
Did you clear the thumbnail cache? (rp-config has a convenient button to do this.)

**Comment by Masamune3210** [comment]
Yep, unregistered the old dll, used rp-config to clean both rp's cache and the system cache, checked some isos to make sure that they weren't showing anything other than the default icon, and then registered the new dll

**Comment by GerbilSoft** [comment]
I'll need to test it on my Win10 VM then. (It seems to have fixed it for Win7, at least...)

**Comment by GerbilSoft** [comment]
I'm not able to reproduce this on Windows 10 v1809. What version of Windows 10 (or 11) are you using?

**Comment by Masamune3210** [comment]
![image](https://github.com/GerbilSoft/rom-properties/assets/1053504/1946a9eb-2def-4027-8f00-094357333d42)

**Comment by GerbilSoft** [comment]
Will set up a Windows 11 22H2 VM tomorrow then. This will probably be the last bugfix I'll look at before releasing v2.2.1.

**Comment by Masamune3210** [comment]
I have good news. Turns out that Windows and its ability to be dumb never ends, and I was actually still running the old build even though it said that it had unregistered it. New DLL generates box arts correctly!
![image](https://github.com/GerbilSoft/rom-properties/assets/1053504/fa84b03a-171c-490e-83f7-e58716db60e4)

**Comment by Masamune3210** [comment]
Unless you can think of anything else you want me to test or last minute fixes for something, I think everything is good on my end now.

**Comment by Masamune3210** [comment]
Something I have noticed is that initially it still generates as the squished thumbnail and then seemingly makes a second pass and fixes the aspect ratio. 
You can see what I am talking about here, the top is generating the correct icon, but the bottom is squished. Eventually, once they catch up with each other, they will all snap to the correct ratio. It's almost like there are two threads trying to generate them, one with the fix and one without

**Comment by Masamune3210** [comment]
Reopening, just in case you want to look into that. If not, feel free to close, it seems like the correct one gets saved to the cache in the end so it just ends up being a visual quirk

**Comment by GerbilSoft** [comment]
That's the icon, which appears to be squished. (If you view file properties, you'll see the squished icon.) I'm not sure *why* it's getting squished, since the squaring is supposed to add columns but not change the aspect ratio...

**Comment by GerbilSoft** [comment]
It seems removing squaring for icons fixes it. I know I had problems with non-square icons before, but that might have been on Windows XP.

I'll change it to only enable squared icons on Windows XP and earlier. (Not sure about IExtractImage; will need to test that later.)

**Comment by GerbilSoft** [comment]
Icon squaring is now disabled on Vista and later. My WinXP VM isn't working properly due to some weird interaction with VirtualBox and SMAP, and reporting a bug to VirtualBox requires registering an Oracle account. I could probably work around this by disabling SMAP, but I'd rather not do that...

**Comment by Masamune3210** [comment]
I truly feel for you, I don't think anybody willingly wants to deal with oracle lol

**Comment by GerbilSoft** [comment]
Closing since this should be fixed in Windows Vista and later. Will need to test XP again sometime...
