### ISSUE TITLE
Some ps2 games never get their boxart

### ISSUE THREAD

**Issue by Masamune3210** [GerbilSoft/rom-properties#386]
I have a number of PS2 games that have backing images in the repo but for some reason they never get their Boxart downloaded. Two examples of games with this issue are SLUS_213.92 and SLUS_210.77

**Comment by Masamune3210** [comment]
![image](https://github.com/GerbilSoft/rom-properties/assets/1053504/164f3a8b-1be3-4ca5-b93d-32f1cb4b753a)
![image](https://github.com/GerbilSoft/rom-properties/assets/1053504/bc241fad-e25b-4c83-9d5f-ed78b8e3b7dc)
![image](https://github.com/GerbilSoft/rom-properties/assets/1053504/84cb9ca3-d547-448d-9c1d-742cd22f5596)
![image](https://github.com/GerbilSoft/rom-properties/assets/1053504/7f4840a2-c129-40d5-b078-5dfed21e9494)

**Comment by GerbilSoft** [comment]
Evolution Skateboarding (SLUS_205.40) also has this problem.

It seems there's something weird with the JPEG files that prevents it from being parsed correctly. Need to figure out why.

**Comment by Masamune3210** [comment]
Does the system have a native parser or are you converting them before feeding them to the system?

**Comment by GerbilSoft** [comment]
Found the problem. Some of the JPEGs on xlenore actually use an Exif container, which has different magic than regular JFIF. RpImageLoader::load() checks the magic numbers to determine which loader to use, and it currently only supports JFIF. Adding the Exif magic numbers should fix this.

**Comment by Masamune3210** [comment]
Glad you got it figured out! A community repo like this is bound to have at least one issue like that since the pics come from all over the place

**Comment by Masamune3210** [comment]
Btw, dont hesitate to let me know if you want to have me test anything to make sure a fix works or not. I'm happy to help as always!
