### ISSUE TITLE
Gamecube Property sheet is blank

### ISSUE THREAD

**Issue by Masamune3210** [GerbilSoft/rom-properties#389]
Getting a weird issue with the latest release with rvz's. No thumbnail is being shown and the property sheet is completely blank save for the header stating that its a Nintendo Gamecube Disk Image
![image](https://github.com/GerbilSoft/rom-properties/assets/1053504/5eac1f2d-1346-471c-a897-37042173a50c)

**Comment by Masamune3210** [comment]
Same thing happens with Wii, maybe a issue with the rvz parser?
![image](https://github.com/GerbilSoft/rom-properties/assets/1053504/6120c14f-b00f-4daa-a25e-8b3e996f4cb6)

**Comment by GerbilSoft** [comment]
```
dd414bc544cddb65f21a49a1c071d0fad17adcc7 is the first bad commit
commit dd414bc544cddb65f21a49a1c071d0fad17adcc7
Author: David Korth <gerbilsoft@gerbilsoft.com>
Date:   Sun Feb 19 00:57:53 2023 -0500

    [libromdata] GameCube: Handle standalone Wii update partitions containing Incrementing Values.
    
    Reported by @johnsanc314.
```
