### ISSUE TITLE
Upgrade fails on Ubuntu 22.04 "Jammy" Jellyfish

### ISSUE THREAD

**Issue by Ntemis** [GerbilSoft/rom-properties#393]
Get:1 https://ppa.launchpadcontent.net/gerbilsoft/ppa/ubuntu jammy/main amd64 rom-properties-data all 2.2.1-1ppa2~jammy2 [57,4 kB]
Get:2 https://ppa.launchpadcontent.net/gerbilsoft/ppa/ubuntu jammy/main amd64 libromdata3 amd64 2.2.1-1ppa2~jammy2 [670 kB]
Get:3 https://ppa.launchpadcontent.net/gerbilsoft/ppa/ubuntu jammy/main amd64 rom-properties-utils amd64 2.2.1-1ppa2~jammy2 [68,2 kB]
Get:4 https://ppa.launchpadcontent.net/gerbilsoft/ppa/ubuntu jammy/main amd64 rom-properties-xdg all 2.2.1-1ppa2~jammy2 [53,4 kB]
Get:5 https://ppa.launchpadcontent.net/gerbilsoft/ppa/ubuntu jammy/main amd64 rom-properties-kf5 amd64 2.2.1-1ppa2~jammy2 [272 kB]
Get:6 https://ppa.launchpadcontent.net/gerbilsoft/ppa/ubuntu jammy/main amd64 rom-properties-thumbnailer-dbus amd64 2.2.1-1ppa2~jammy2 [61,9 kB]
Get:7 https://ppa.launchpadcontent.net/gerbilsoft/ppa/ubuntu jammy/main amd64 rom-properties-gtk3 amd64 2.2.1-1ppa2~jammy2 [203 kB]
Get:8 https://ppa.launchpadcontent.net/gerbilsoft/ppa/ubuntu jammy/main amd64 rom-properties-cli amd64 2.2.1-1ppa2~jammy2 [63,9 kB]
Get:9 https://ppa.launchpadcontent.net/gerbilsoft/ppa/ubuntu jammy/main amd64 rom-properties-lang all 2.2.1-1ppa2~jammy2 [120 kB]
Get:10 https://ppa.launchpadcontent.net/gerbilsoft/ppa/ubuntu jammy/main amd64 rom-properties-all amd64 2.2.1-1ppa2~jammy2 [46,8 kB]
Fetched 1617 kB in 5s (331 kB/s)          
(Reading database ... 601868 files and directories currently installed.)
Preparing to unpack .../0-rom-properties-data_2.2.1-1ppa2~jammy2_all.deb ...
Unpacking rom-properties-data (2.2.1-1ppa2~jammy2) over (2.1-1ppa2~jammy2) ...
Selecting previously unselected package libromdata3.
Preparing to unpack .../1-libromdata3_2.2.1-1ppa2~jammy2_amd64.deb ...
Unpacking libromdata3 (2.2.1-1ppa2~jammy2) ...
Preparing to unpack .../2-rom-properties-utils_2.2.1-1ppa2~jammy2_amd64.deb ...
Unpacking rom-properties-utils (2.2.1-1ppa2~jammy2) over (2.1-1ppa2~jammy2) ...
dpkg: error processing archive /tmp/apt-dpkg-install-2iFraI/2-rom-properties-uti
ls_2.2.1-1ppa2~jammy2_amd64.deb (--unpack):
 trying to overwrite '/usr/share/thumbnailers/rom-properties.thumbnailer', which
 is also in package rom-properties-gtk3 2.1-1ppa2~jammy2
Preparing to unpack .../3-rom-properties-xdg_2.2.1-1ppa2~jammy2_all.deb ...
Unpacking rom-properties-xdg (2.2.1-1ppa2~jammy2) over (2.1-1ppa2~jammy2) ...
Preparing to unpack .../4-rom-properties-kf5_2.2.1-1ppa2~jammy2_amd64.deb ...
Unpacking rom-properties-kf5 (2.2.1-1ppa2~jammy2) over (2.1-1ppa2~jammy2) ...
Preparing to unpack .../5-rom-properties-thumbnailer-dbus_2.2.1-1ppa2~jammy2_amd
64.deb ...
Unpacking rom-properties-thumbnailer-dbus (2.2.1-1ppa2~jammy2) over (2.1-1ppa2~j
ammy2) ...
Preparing to unpack .../6-rom-properties-gtk3_2.2.1-1ppa2~jammy2_amd64.deb ...
Unpacking rom-properties-gtk3 (2.2.1-1ppa2~jammy2) over (2.1-1ppa2~jammy2) ...
Preparing to unpack .../7-rom-properties-cli_2.2.1-1ppa2~jammy2_amd64.deb ...
Unpacking rom-properties-cli (2.2.1-1ppa2~jammy2) over (2.1-1ppa2~jammy2) ...
Preparing to unpack .../8-rom-properties-lang_2.2.1-1ppa2~jammy2_all.deb ...
Unpacking rom-properties-lang (2.2.1-1ppa2~jammy2) over (2.1-1ppa2~jammy2) ...
Preparing to unpack .../9-rom-properties-all_2.2.1-1ppa2~jammy2_amd64.deb ...
Unpacking rom-properties-all (2.2.1-1ppa2~jammy2) over (2.1-1ppa2~jammy2) ...
Errors were encountered while processing:
 /tmp/apt-dpkg-install-2iFraI/2-rom-properties-utils_2.2.1-1ppa2~jammy2_amd64.de
b
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by GerbilSoft** [comment]
Known issue due to moving files between packages. This hopefully won't happen again in future releases.
