### ISSUE TITLE
GameBoy multicarts: MBC1M and MMM01

### ISSUE THREAD

**Issue by DankRank** [GerbilSoft/rom-properties#394]
Multicarts generally have multiple headers embedded within. The Hardware field can be made more precise if we detect these headers. (It'd be nice to be able to view header info for each game in a multicart, but that's not what this issue is about)

There are some multicarts that use MBC1 in a non-standard configuration, often called [MBC1M](https://gbdev.io/pandocs/MBC1.html#mbc1m-1-mib-multi-game-compilation-carts). A more descriptive name would be "MBC1-based 1 MiB multicart". Here's the difference between regular MBC1 and MBC1M:
```
1 MiB MBC1 game:
     |                       ROM
     | A19  A18  A17  A16  A15  A14  A13 A12 A11 A10...
     --------------------------------------------------
        |    |    |    |    |    |    |   |   |   |
  N/C   |    |    |    |    |    |    |   |   |   |
   |    |    |    |    |    |    |    |   |   |   |
------------------------------------  |   |   |   |
|AA14 AA13 RA18 RA17 RA16 RA15 RA14| A13 A12 A11 A10...
|  BANK2  |          BANK1         |    Cart Edge
|              MBC1                |

1 MiB MBC1 multicart:
     |                       ROM
     | A19  A18  A17  A16  A15  A14  A13 A12 A11 A10...
     --------------------------------------------------
      /    /      |    |    |    |    |   |   |   |
     /    / N/C   |    |    |    |    |   |   |   |
    /    /   |    |    |    |    |    |   |   |   |
------------------------------------  |   |   |   |
|AA14 AA13 RA18 RA17 RA16 RA15 RA14| A13 A12 A11 A10...
|  BANK2  |          BANK1         |    Cart Edge
|              MBC1                |
```

BANK2 register can affect both the "fixed" bank and the switchable bank, so it makes an ideal game switch. This setup allows for up to three 256 KiB MBC1 games + a menu to be put on a single 1 MiB cartridge.

How to detect MBC1M? First of all, the ROM size is always 1 MiB, and the (first) header reports MBC1. The menu is at $00000, and the two/three games are at $40000, $80000, $C0000. Mooneye-gb uses a heuristic where [3 out of 4 locations must have the logo](https://github.com/Gekkio/mooneye-gb/blob/3856dcbca82a7d32bd438cc92fd9693f868e2e23/core/src/config/cartridge.rs#L400-L419). However, it's simpler to just check the logo at 0x40000.

I took the no-intro romset (just gb, no gbc) and filtered it down to 1 MiB "MBC1" games with the logo in at least 2 locations, and got this list of MBC1M games:

| ROM                                                 | 0x00000          | 0x40000          | 0x80000          | 0xC0000         |
|-----------------------------------------------------|------------------|------------------|------------------|-----------------|
| Bomberman Collection (Japan) (SGB Enhanced).gb      | BOMCOL           | BOMBER BOY       | BOMBERMAN GB     | BOMBER MAN GB 2 |
| Genjin Collection (Japan) (SGB Enhanced).gb         | GENCOL           | GB GENJIN        | GBGENJIN2        | GB GENJIN LAND  |
| Momotarou Collection (Japan) (SGB Enhanced).gb      | MOMOCOL          | MOMOTARO DENGEKI | SUPER MOMOTETU 2 | (None)          |
| Mortal Kombat & Mortal Kombat II (Japan).gb         | MORTALKOMBAT DUO | MORTAL KOMBAT    | MORTAL KOMBAT II | (None)          |
| Mortal Kombat & Mortal Kombat II (USA, Europe).gb   | MORTALKOMBATI&II | MORTAL KOMBAT    | MORTAL KOMBAT II | (None)          |
| Super Chinese Land 1-2-3' (Japan) (SGB Enhanced).gb | SUPERCHINESE 123 | SUPERCHINESELAND | SUPER CHINESE 2  | SUPER CHINESE 3 |

However there are two ROMs that did match my search, but which aren't MBC1M. As it turns out these are [MMM01](https://gbdev.io/pandocs/MMM01.html) carts. MMM01 is a multicart mapper that is compatible with MBC1 games. Crucially, unlike other mappers, it doesn't map first 32K of the ROM on boot. Instead it maps the *last* 32K. Here's the two aforementioned ROMs:

| ROM                                                                                                                    | 0x00000          | 0x40000    | 0x80000          | 0xC0000 | 0xF8000         |
|------------------------------------------------------------------------------------------------------------------------|------------------|------------|------------------|---------|-----------------|
| Mani 4 in 1 - Takahashi Meijin no Bouken-jima II + GB Genjin + Bomber Boy + Milon no Meikyuu Kumikyoku (China) (Ja).gb | GB GENJIN        | BOMBER BOY | BOUKENJIMA2      | (None)  | BOUKENJIMA2 SET |
| Momotarou Collection 2 (Japan) (SGB Enhanced).gb                                                                       | MOMOTARODENGEKI2 | (None)     | MOMOTAROU GAIDEN | (None)  | MOMOCOL2        |

Notice how the main header is at the end of the ROM. Rom-properties displays the information from the first bank, which corresponds to one of the included games and not the cartridge as a whole. Emulators which don't support MMM01 will also just run the first game.

Also note how Mani 4 in 1 passes all the checks for MBC1M. For this reason MMM01 should be checked before MBC1M.

Taking all of the above into consideration, the logic for determining the hardware type should be something like this: (assuming the rom is already detected as GB by checking the logo at 0x104)
```py
def valid_header(i):
    return rom[i+0x104:i+0x134] == nintendo_logo
if (len(rom)>0x8000 and                                  # the ROM is at bigger than 32K
        valid_header(len(rom)-0x8000) and                # there's a header in last 32K
        rom[len(rom)-0x8000+0x147] in (0x0B,0x0C,0x0D)): # it claims to be MMM01
    parse_header(len(rom)-0x8000) # use the header in the last 32K instead of the one at 0
else:
    parse_header(0) # use the regular header
    if (len(rom) == 0x100000 and               # the ROM is 1M
            rom[0x147] in (0x01,0x02,0x03) and # it claims to be MBC1
            valid_header(0x40000)):            # there's a header at 256K
        set_hardware_type('MBC1M') # change the type from MBC1 to MBC1M
```

After this is implemented, title screens for MMM01 multicarts will need to be added to rpdb.

**Comment by GerbilSoft** [comment]
Need to rename filenames on RPDB for the following ROM images:

Mani 4 in 1 - Genki Bakuhatsu Gambaruger + Zettai Muteki Raijin-Oh + Zoids Densetsu + Miracle Adventure of Esparks - Ushinawareta Seiseki Perivron (China) (Ja).gb
Mani 4 in 1 - Genki Bakuhatsu Gambaruger + Zettai Muteki Raijin-Oh + Zoids Densetsu + Miracle Adventure of Esparks - Ushinawareta Seiseki Perivron (China) (Ja).sav
Mani 4 in 1 - R-Type II + Saigo no Nindou + Ganso!! Yancha Maru + Shisenshou - Match-Mania (China) (Ja).gb
Mani 4 in 1 - Takahashi Meijin no Bouken-jima II + GB Genjin + Bomber Boy + Milon no Meikyuu Kumikyoku (China) (Ja).gb
Momotarou Collection 2 (Japan) (SGB Enhanced).sgb
Taito Variety Pack (Japan).gb

mGBA says it has "partial" support for MMM01; not sure about MBC1M. I'll probably need to retake all of these screenshots at some point once that support is improved.

**Comment by DankRank** [comment]
Hi, regarding that commit you made, MMM01 can actually (in theory) be any power of two from 64 KiB up to 8 MiB. In practice it's only 1 MiB and 512 KiB. Also, the "Mani 4 in 1" roms have their mapper set to 0x11 (MBC3) for some reason. It's still important to check that the mapper is 0x0B, 0x0C, 0x0D or 0x11 ([SameBoy checks for these four](https://github.com/LIJI32/SameBoy/blob/7e6f1f866e89430adaa6be839aecc4a2ccabd69c/Core/mbc.c#L169-L178)), because there are quite a few unlicensed games which aren't MMM01, yet have the logo in the last 32K. (For most of them it's because they put the logo in *every* 32K).

<details>
<summary>licensed games with logo in last 32K (MMM01)</summary>

```
Nintendo - Game Boy/Mani 4 in 1 - Takahashi Meijin no Bouken-jima II + GB Genjin + Bomber Boy + Milon no Meikyuu Kumikyoku (China) (Ja).zip
mapper: 11      len: 1024K      headers: 5      title: b'BOUKENJIMA2 SET'
Nintendo - Game Boy/Momotarou Collection 2 (Japan) (SGB Enhanced).zip
mapper: 0D      len: 1024K      headers: 3      title: b'MOMOCOL2'
Nintendo - Game Boy/Mani 4 in 1 - Genki Bakuhatsu Gambaruger + Zettai Muteki Raijin-Oh + Zoids Densetsu + Miracle Adventure of Esparks - Ushinawareta Seiseki Perivron (China) (Ja).zip
mapper: 11      len: 512K       headers: 5      title: b'GANBARUGA SET'
Nintendo - Game Boy/Mani 4 in 1 - R-Type II + Saigo no Nindou + Ganso!! Yancha Maru + Shisenshou - Match-Mania (China) (Ja).zip
mapper: 11      len: 512K       headers: 5      title: b'RTYPE 2 SET'
Nintendo - Game Boy/Mani 4 in 1 - Bubble Bobble + Elevator Action + Chase H.Q. + Sagaia (China) (En).zip
mapper: 11      len: 512K       headers: 5      title: b'BUBBLEBOBBLE SET'
Nintendo - Game Boy/Taito Variety Pack (Japan).zip
mapper: 0B      len: 512K       headers: 5      title: b'VARIETY PACK'
```
</details>

<details>
<summary>unlicensed games with logo in last 32K (not MMM01)</summary>

```
Nintendo - Game Boy/Spiritual Warfare (USA) (Unl).zip
mapper: 00      len: 256K       headers: 8      title: b''
Nintendo - Game Boy/Aprilia - DiTech Interface (Unknown) (Unl) [b].zip
mapper: 01      len: 256K       headers: 16     title: b'APP'
Nintendo - Game Boy/Joshua & the Battle of Jericho (USA) (Unl).zip
mapper: 00      len: 128K       headers: 4      title: b''
Nintendo - Game Boy/Doctor GB Card 4M (World) (Unl).zip
mapper: 00      len: 512K       headers: 13     title: b'DEMO2'
Nintendo - Game Boy/Exodus - Journey to the Promised Land (USA) (Unl).zip
mapper: 00      len: 128K       headers: 4      title: b''
Nintendo - Game Boy/King James Bible (USA) (Unl).zip
mapper: 00      len: 1024K      headers: 32     title: b''
Nintendo - Game Boy/NIV Bible & the 20 Lost Levels of Joshua (USA) (Unl).zip
mapper: 00      len: 2048K      headers: 64     title: b''
Nintendo - Game Boy Color/Fengkuang Dafuweng (Taiwan) (Unl) (Alt).zip
mapper: 01      len: 2048K      headers: 2      title: b''
Nintendo - Game Boy Color/Peugeot - Orbital Diagnostic System (Unknown) (Unl) [b].zip
mapper: 01      len: 1024K      headers: 64     title: b'APP'
Nintendo - Game Boy Color/Guaishou Go! Go! II (Taiwan) (Unl).zip
mapper: 03      len: 1024K      headers: 3      title: b'KIRBY2'
```
</details>

**Comment by GerbilSoft** [comment]
0x0B, 0x0C, 0x0D are all handled by the cart_type stuff as MMM01.
0x11 is MBC3, but it's MBC3 with no extra features, so I'll have it check for that instead of any MBC3.

**Comment by GerbilSoft** [comment]
Added title screens for:

Momotarou Collection 2 (Japan) (SGB Enhanced).sgb
![Momotarou Collection 2 (Japan) (SGB Enhanced).sgb](https://rpdb.gerbilsoft.com/gb/title/SGB/MOMOCOL2-18-J.png)

Taito Variety Pack (Japan).gb
![Taito Variety Pack (Japan).gb](https://rpdb.gerbilsoft.com/gb/title/DMG/VARIETY%20PACK-C0-J.png)

ROM Properties 2.3 (once it's released) or git master (once this branch is merged) will be needed in order for these title screens to show up properly. The older versions will end up showing the title screen of the first internal ROM in each collection:

Momotarou Collection 2 (Japan) (SGB Enhanced).sgb
![Momotarou Collection 2 (Japan) (SGB Enhanced).sgb](https://rpdb.gerbilsoft.com/gb/title/SGB/MOMOTARODENGEKI2-18-J.png)

Taito Variety Pack (Japan).gb
![Taito Variety Pack (Japan).gb](https://rpdb.gerbilsoft.com/gb/title/DMG/SAGAIA-C0-J.png)

For these three ROMs, I'm not sure if mGBA is emulating the mapper correctly, so I haven't taken screenshots:
* Mani 4 in 1 - Genki Bakuhatsu Gambaruger + Zettai Muteki Raijin-Oh + Zoids Densetsu + Miracle Adventure of Esparks - Ushinawareta Seiseki Perivron (China) (Ja).gb
* Mani 4 in 1 - R-Type II + Saigo no Nindou + Ganso!! Yancha Maru + Shisenshou - Match-Mania (China) (Ja).gb
* Mani 4 in 1 - Takahashi Meijin no Bouken-jima II + GB Genjin + Bomber Boy + Milon no Meikyuu Kumikyoku (China) (Ja).gb

**Comment by DankRank** [comment]
The 256 KiB Mani 4 in 1 is [M161](https://gbdev.io/pandocs/M161.html), which has the menu at the start, and games every 32K after that. Interestingly the mapper number is 0x10 (also MBC3) I wonder if this is a result of some decimal/hex confusion.
