### ISSUE TITLE
PE machine value 0x0601 == PowerPC big-endian (classic Mac)

### ISSUE THREAD

**Issue by Wack0** [GerbilSoft/rom-properties#396]
In the 1990s, Microsoft released a Visual C++ cross-compiler to classic Mac, with m68k and big-endian PowerPC cross compilers.

Both of these emit PEs; the m68k machine value is known to ROM Properties, but the big-endian PowerPC one is not.

Machine value 0x0601 (specified because PowerPC 601, naturally) is used for these big-endian PowrePC PEs.

Example binary: https://archive.org/download/VCPP4.00Macintosh/VCPP-4.00-Macintosh.iso/MSDEV%2FMAC%2FMPPC%2FLIB%2FMSVCRT40.DLL

**Comment by GerbilSoft** [comment]
Interesting... There's another PowerPC big-endian value, 0x1F2, which is used on Xbox 360.

I'll add this one and mark the other one as ~~PPC 64-bit BE~~ PPC BE (Xbox 360). (It's also 32-bit, not 64-bit, even though Xbox 360 has a 64-bit CPU...)

**Comment by Wack0** [comment]
Yeah, I think MS totally forgot about the old classic mac stuff when they revived a big-endian powerpc compiler for xbox 360

I think the main difference is the older Mac one has a bunch of additional relocations that only make sense on that platform.

For the record, the official name of this one is `IMAGE_FILE_MACHINE_MPPC_601`.

**Comment by GerbilSoft** [comment]
Added `IMAGE_FILE_MACHINE_MPPC_601` after the above commit.

I'll note that some stuff still seems to be a bit wonky. For instance, it shows "Subsystem: Console 1024.32768". Byteswapping the values results in "4.128", which still seems weird. Also, import/export tables aren't showing up, possibly due to big-endian values elsewhere in the DLL. I'll look into this more later.

**Comment by Wack0** [comment]
Yeah, I noticed that too.

The linker stashes some platform-related version numbers in there but it treats both of them as little-endian DWORD internally so I'm still not sure what's up there.

It appears the export tables are emitted inside a structure called the "loader header", this structure is placed at the start of the ".ppcldr" section (and appears to have offsets to additional sub-structures including imports/exports), and period-correct dumpbin.exe can dump it.

(By the way, you renamed the Xbox 360 big-endian PowerPC machine value to `IMAGE_FILE_MACHINE_POWERPCBEX`, which you might want to revert, as the official name for that is indeed `IMAGE_FILE_MACHINE_POWERPCBE`...)
