### ISSUE TITLE
ROM Properties page displays incorrectly with StartAllBack installed 

### ISSUE THREAD

**Issue by kristibektashi** [GerbilSoft/rom-properties#399]
When you install StartAllBack and enable dark mode in the settings, the File Explorer properties dialogs also show in dark mode. However this causes issues with the Rom Properties page where some parts are still bright and the text is unreadable. 
![image](https://github.com/GerbilSoft/rom-properties/assets/40217426/86ed2bef-5dfa-409a-8809-0fde14df6ca7)![image](https://github.com/GerbilSoft/rom-properties/assets/40217426/ceb9a036-02e9-4d81-93a9-61f2cf3f3f0c)

**Comment by ionuttbara** [comment]
+1

**Comment by GerbilSoft** [comment]
Please test the DLLs in this build (once it finishes): https://ci.appveyor.com/project/GerbilSoft/rom-properties/builds/48949174/job/yuae38ythykwmx91

The main fix was forwarding WM_CTLCOLOR* messages to the parent dialog. StartAllBack intercepts those messages and remaps them for use with its enhanced dark mode functionality.

Some stuff still isn't working right now:
* "Warning" messages don't appear in red. A "warning" message shows up in certain cases, e.g. if you open a Dreamcast VMI file and the corresponding VMS file is missing (or vice-versa).
* The "Options" button still has black text.

I'll note that the tab background color still isn't quite right. (It's too dark compared to other tabs.) I'll need to do some more investigation into figuring that out.

**Comment by ionuttbara** [comment]
for canary build is ok, but i will see in normal windows 11 installation. this white part is coming for SaB
![image](https://github.com/GerbilSoft/rom-properties/assets/76656855/e2355d01-9737-4aab-9c58-16cbf22a874a)

**Comment by ionuttbara** [comment]
this is good. in normal windows 11. i can say this is fixed. 😊 the options text color is not changed.
![image](https://github.com/GerbilSoft/rom-properties/assets/76656855/47abf7bd-cd4c-4b11-adbb-bc66e580a6e2)

**Comment by GerbilSoft** [comment]
Marking as fixed in 2.3.
