### ISSUE TITLE
Causing certain Windows apps to crash when NDS files are packed into CIA files

### ISSUE THREAD

**Issue by ApacheThunder** [GerbilSoft/rom-properties#423]
Using Windows 10 Pro 64Bit I have installed this and noticed some issues. If I download a CIA file in FireFox (CIA file being installable content container used for 3DS consoles) that is a NDS built CIA file, it causes Firefox to crash when viewing download history. Since I can't clear download history without viewing it I had to revert the underlying database file to an older version from a drive image backup I happened to make the day before (so I could also avoid clearing my web history)

But there's more! :P

WinRar also crashes when said CIA files are present in RAR/ZIP archives when trying to view them in WinRAR's filebrowser. I can still extract said archives if I extract them via right click context menus though. Only the filebrower UI dies when trying to view said archives containing NDS CIAs.

I'm not sure why this is happening but I think perhaps special handling for CIA files needs to be added as it appears to be causing issues (this issue might crop up in any file containing a DS rom that doesn't have the DS rom in the right place aka a non NDS rom that has a DS rom embedded in it somewhere that is offset from 0x0 in the file., CIA files seem to especially trigger issues with this so this might not be a CIA file specific issue. Then again it could just be something with the CIA format that is triggering this.  Won't know until it's looked into) In fact it might be an interaction with an unrelated tool I might have installed years back to enable icon display for CIA files....Maybe CIA files should be blacklisted. I will have to try and hunt down what I installed for CIA files as it's been years. :P

This may impact more file browser UI on other apps but WinRar and Firefox were the big ones I've notice it on so far.

**Comment by GerbilSoft** [comment]
I'm not seeing this sort of crash on Gentoo Linux with KDE Plasma 6 when viewing the TWiLightMenu CIAs. I'll test on my Windows VMs next.

**Comment by ApacheThunder** [comment]
Ok I might have found the cause. It was a conflict with an older shell extension by the name of 3DS Shell. Uninstalled it, then reinstalled this one. WinRar no longer crashing. But now I can't delete the folder I installed this from...so force deleted it with explorer killed by task manager. (used task manager's file browse UI to navigate to the folder so I could remove it).

This broke icons for nds/cias...so guessing the install script just linked it to the folder I extracted on Desktop...That's odd. I think maybe a proper install folder needs to be setup then have it install from there. Seems like a bad idea to leave a constantly locked folder stuck from what ever random location it was installed from. :P

Now I got to try and deregister it again and reinstall from a manually created folder in Program Files. :P

EDIT: Ok was able to reinstall. I found I had created a NDSRomProp folder in Program files I had initially installed it to. I updated the files and ran the install exe again. No issues re-registering anything.

Also confirmed CIA files aren't crashing Firefox/WinRar anymore.


Seems to have just been a bad conflict with an older extension I forgot I had installed nearly a decade back. :P

Not sure how you could handle this. Maybe check for 3DS-Shell and warn the user. I honestly forgot I had it. :P

**Comment by GerbilSoft** [comment]
I could potentially add a check in the installer. I'd need the 3DS-Shell DLL info to do that.

(...and maybe some day use a proper installer instead of what we have now)

**Comment by ApacheThunder** [comment]
It was this where I found it:

https://gbatemp.net/threads/3dsshellext-show-cia-3dsx-smdh-icons-in-windows.468928/

Some of the links are dead. I used web archive (thank god that's working again. :P ) to download an older version just so I could run their uninstall script. :P

I think web archive still has most of the versions so you can use that if you want to add checks for it.

And yeah a proper installer would be helpful. I forgot how this installed so after I quickly fixed everything I found I had an undeletable folder on my desktop. ...that was an annoying surprise. :P
