### ISSUE TITLE
Ubuntu 24.04 ppa lib error

### ISSUE THREAD

**Issue by Blad3forc3** [GerbilSoft/rom-properties#426]
sudo apt install rom-properties-all
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 rom-properties-gtk4 : Depends: libromdata2 but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by GerbilSoft** [comment]
Which version of Ubuntu is this?

EDIT: Never mind, found it in the control file. Looks like a copy/paste error. I'll rebuild the Ubuntu packages for 24.04 later tonight. (and hopefully 24.10 once I figure out the Qt6 build issues there)

**Comment by Blad3forc3** [comment]
Operating System: Kubuntu 24.04
KDE Plasma Version: 5.27.11
KDE Frameworks Version: 5.115.0
Qt Version: 5.15.13
Kernel Version: 6.5.0-35-generic (64-bit)
Graphics Platform: Wayland
Processors: 4 × Intel® Core™ i5-4460 CPU @ 3.20GHz
Memory: 15.5 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: H81M-S2H

**Comment by GerbilSoft** [comment]
Pushed a packaging fix so rom-properties-gtk4 now depends on libromdata5 instead of libromdata2, so you should be able to update the packages "soon".
