### ISSUE TITLE
No Thumbnails  after install

### ISSUE THREAD

**Issue by Conan179** [GerbilSoft/rom-properties#427]
Hello@all.
After installing v2.4, thumbnails are no longer created for folders. Only uninstalling fixes the problem for me.
Win 11 24H2

**Comment by GerbilSoft** [comment]
This is likely related to the Wii U Package thumbnailing feature, which registers a custom thumbnailer for directories.

In rp-config, there's an option "Enable thumbnailing and metadata extraction of directory-based packages". Does disabling this option allow directories to be thumbnailed properly with 2.4, or does it still fail regardless? If it fails regardless, I'll need to revert this change for Windows and/or figure out how to get it to properly fall back to the system thumbnailer if the directory is not a Wii U package.

**Comment by Conan179** [comment]
Unfortunately it makes no difference whether the option is on or off, only when uninstalling are the thumbnails created again :(

**Comment by GerbilSoft** [comment]
It seems that in order to fix this, I'll need to find the CLSID of the IThumbnailProvider that Windows internally uses to create directory thumbnails. Otherwise, the only option is to provide an option to not register for directories, since it's basically "all directories or no directories".

**Comment by GerbilSoft** [comment]
Found a workaround. IThumbnailProvider isn't used for directories in rom-properties anyway; IExtractImage is. If IExtractImage returns E_FAIL instead of S_OK for directories, it'll revert to standard directory thumbnailing, instead of just showing an empty folder.

Will push a v2.4.1 for Windows in a bit.

**Comment by GerbilSoft** [comment]
https://github.com/GerbilSoft/rom-properties/releases/tag/v2.4.1

**Comment by Conan179** [comment]
Thanks, my problem is fixed. :)
