### ISSUE TITLE
5 keys missing from `keys.conf.example`

### ISSUE THREAD

**Issue by RuinTD** [GerbilSoft/rom-properties#429]
Hello. There are 5 keys missing from `keys.conf.example` that can be set in the Key Manager GUI. These keys are:
- `wup-starbuck-wiiu-common`
- `cat-starbuck-wiiu-common`
- `ctr-spi-boot`
- `ctr-dev-spi-boot`
- `ctr-dev-FixedCryptoKey`

**Comment by GerbilSoft** [comment]
Added, thanks for reporting.
