### ISSUE TITLE
[Bug Report] EXE/DLL files causes a crash

### ISSUE THREAD

**Issue by xxmichibxx** [GerbilSoft/rom-properties#432]
Starting with version 2.4, the Explorer crashes with error code 0xc000041d whenever I try to open the ROM-Properties tab within the properties of an EXE or DLL file. Other files like 3DS/CIA ROMs works just fine. This issue was not present in previous versions (e.g., 2.3).

**Steps to reproduce:**
- Install ROM-Properties version 2.4 or later.
- Right-click on any EXE or DLL file.
- Select "Properties".
- Navigate to the "ROM-Properties" tab.
- The Explorer crashes immediately.

**Expected behavior:** The ROM-Properties tab should open without crashing the Explorer.

ROM-Properties version: 2.4.1
Operating system: Windows 10 IoT Enterprise LTSC 2021 x64 (21H2)
Affected DLL: msvcrt.dll (version 7.0.19041.3636)

**Additional information:**
- I have attached a report for the analyzed crash dump file (WinDbg) for further investigation
- I have installed the latest Visual C++ Redistributables from here (https://github.com/abbodi1406/vcredist)
- All previous version of ROM-Properties where delete successfully before the upgrading to newer versions
- The new verison works fine with Windows 7 Enterprise N x64

[explorer.exe-WinDbg.txt](https://github.com/user-attachments/files/18028897/explorer.exe-WinDbg.txt)

**Comment by GerbilSoft** [comment]
Reproduced this on Win10 1809; could not reproduce on Win7, as you said.

Will attempt to bisect the issue to figure out what's going on.

**Comment by GerbilSoft** [comment]
Well this is interesting. Building the latest from git as a Debug build works fine, but as a Release version, it crashes. That will definitely make debugging harder...

**Comment by Masamune3210** [comment]
Maybe some optimization present when built as release but is left out for ease of debugging when not?

**Comment by GerbilSoft** [comment]
I bisected it to 59c3d23285b751f807a4889099557604fdbf3cf8, but reverting it didn't actually fix the issue in the current build.

What *actually* seems to be the issue:

    lvColumn.pszText = const_cast<LPTSTR>(tstr.c_str());

This *used* to work just fine on both Windows 7 and Windows 10, but it's crashing now on Windows 10. Using a TCHAR[] buffer instead of a tstring seems to fix it, because the TCHAR[] buffer is writable. This *doesn't* make any sense whatsoever. It might be some weird compiler bug with std::wstring with MSVC 17.6.5 and it only manifests on Windows 10.

**Comment by GerbilSoft** [comment]
...it seems that even with this fix, it causes some of the ListView headers to show up as garbage. I'm not really sure what's going on here, and this will take some more debugging.

**Comment by GerbilSoft** [comment]
And it turns out that wasn't the problem. Narrowed it down to this:

```
lvData.setInitialSort(listDataDesc.col_attrs.sort_col, listDataDesc.col_attrs.sort_dir);
```

Removing the initial sort fixes everything. The question is why.

**Comment by GerbilSoft** [comment]
Well, that was stupid. HDITEM::mask wasn't initialized before calling Header_GetItem() or Header_SetItem(). It's just dumb luck that it's not crashing on Windows 7, or that previous versions didn't crash on Windows 10.

Thanks for the report. I'll probably release v2.5 this weekend with this fix and some other stuff, including support for J2ME JARs and extracted Wii U packages.
