### ISSUE TITLE
Update Amiibo Data

### ISSUE THREAD

**Issue by cheatfreak47** [GerbilSoft/rom-properties#53]
Currently these are missing:

Yoshi's Woolly World Series
Poochy	00800102	035D0302

Zelda Breath of the Wild Series
Link (Archer)	01000000	03530902
Link (Rider)	01000000	03540902
Guardian	01400000	03550902
Zelda	01010000	03560902
Bokoblin	01410000	035C0902

Qbby of Boxbox is missing too but we don't know the ID of that yet

**Comment by GerbilSoft** [comment]
Added in commit de39477aff5d22c857be08a586cc5e298501cac9.
