### ISSUE TITLE
Switch Wii/GC games to use their 2D Covers instead of Disc Images

### ISSUE THREAD

**Issue by cheatfreak47** [GerbilSoft/rom-properties#56]
A common problem with the GameTDB is that it actually has a huge catalog of missing disc arts.
Because of this, I propose that you switch to using the 2D Cover Images instead. 

In the future when you get around to #52 , you could make the disc art an option along with the 3D covers if you want, but I think the 2D Box Arts are the most viable default option.

**Comment by GerbilSoft** [comment]
#52 is one of the main blockers for 1.0. Not sure if I'll have it default to cover art, but it will support falling back to cover art if disc scans aren't available.

Other blockers are finishing up 3DS support (including encryption key verification for 3DS and Wii) and Windows icon support.

**Comment by cheatfreak47** [comment]
ah okay- still, the 2D cover arts are generally more well supported then the disc art, so might be worth considering- and when 52 rolls on, It'd be good to have an option to pick what Image you want. (Disc, 3D, 2D)
