### ISSUE TITLE
QT_PLUGIN_INSTALL_DIR path problem

### ISSUE THREAD

**Issue by shadowwa** [GerbilSoft/rom-properties#69]
When I'm trying to build rom-properties on mageia, since commit 303169e419a8d474e196e9224217ca7a041b0ed8 the rom-properties-kde5.so ends up in bad directory:

    /usr/plugins/rom-properties-kde5.so

while it should be in

     /usr/lib64/qt5/plugins/rom-properties-kde5.so

If I try qtpaths, I got the good path
```
qtpaths --plugin-dir
/usr/lib64/qt5/plugins
```
```
qtpaths --install-prefix
/usr/lib64/qt5
```
but in the src/kde/kde5/CMakeLists.txt 
after the REPLACE_HARDCODED_PREFIX, I got
```
PLUGIN_INSTALL_DIR=/usr/plugins
QT_PLUGIN_INSTALL_DIR=/usr/plugins
```

**Comment by GerbilSoft** [comment]
The install prefix should be /usr, not /usr/lib64/qt5.

I'll change it so it will handle it somewhat differently if the prefix doesn't match CMAKE_INSTALL_PREFIX.

**Comment by GerbilSoft** [comment]
@shadowwa I committed a change that should fix this. Can you test it and report back?

**Comment by shadowwa** [comment]
It's working fine now.
