### ISSUE TITLE
[GTK+] User configuration program.

### ISSUE THREAD

**Issue by GerbilSoft** [GerbilSoft/rom-properties#73]
<a href="https://github.com/GerbilSoft"><img src="https://avatars2.githubusercontent.com/u/6764716?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [GerbilSoft](https://github.com/GerbilSoft)**
_Thursday May 25, 2017 at 00:38 GMT_
_Originally opened as https://github.com/GerbilSoft/rom-properties.reworking/issues/73_

----

Port the KDE rp-config from #62 to GTK+.

**Comment by bell07** [comment]
I am XFCE user and was wondering about the new "Rom properties configurator" menu entry in version 1.9. The menu entry does not work since the rp-confg returns `Could not find rp_show_config_dialog() in any installed rom-properties plugin.`

Is it possible to install the desktop file and rp-config binary only in case, if no plugin was build?

**Comment by GerbilSoft** [comment]
You can install the KDE UI frontend (rom-properties-kf5) to use rp-config, though that will pull in a lot of other dependencies.

I'm going to take a look at starting an rp-config GTK frontend, maybe over the weekend.

**Comment by GerbilSoft** [comment]
I started a GTK+ frontend with compatibility for GTK2, GTK3, and GTK4. (GTK2 is untested; GTK4 works in theory, but GTK4 is crashing in Mesa on my system for some reason.)

If you can build from source, test this branch: https://github.com/GerbilSoft/rom-properties/tree/feature/rp-config-gtk
The GTK+ version has four tabs so far: Image Types, Systems, Options, and Thumbnail Cache.

Note that the rp-config binary itself is merely a stub. It calls an exported function in the UI frontends to run the actual rp-config dialog. Hence, installing the KF5 frontend would result in rp-config working on your system, since it provides one, though that's using Qt5 instead of GTK.

**Comment by GerbilSoft** [comment]
Implemented with the merge of the [feature/rp-config-gtk](https://github.com/GerbilSoft/rom-properties/tree/feature/rp-config-gtk) branch in commit 3044084b99f6e1b6e0d31e33d474ca956c3de790.
