### ISSUE TITLE
cmake can't find NASM on Win 10

### ISSUE THREAD

**Issue by GerbilSoft** [GerbilSoft/rom-properties#79]
<a href="https://github.com/lilggamegenuis"><img src="https://avatars3.githubusercontent.com/u/6175821?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lilggamegenuis](https://github.com/lilggamegenuis)**
_Sunday Jun 11, 2017 at 03:17 GMT_
_Originally opened as https://github.com/GerbilSoft/rom-properties.reworking/issues/79_

----

cmake is unable to find NASM for libjpeg-turbo SIMD functions.
cmake is 3.8.1
OS is Windows 10 Pro Version 1607 (OS Build 14393.1198)
Full NASM path is "C:\Program Files\NASM\nasm.exe" 
(32-bit would be in "C:\Program Files (x86)\NASM\nasm.exe")

**Comment by GerbilSoft** [comment]
<a href="https://github.com/DankRank"><img src="https://avatars2.githubusercontent.com/u/4050457?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [DankRank](https://github.com/DankRank)**
_Sunday Jun 11, 2017 at 08:40 GMT_

----

I think you need to manually specify it.

I just put my 64-bit nasm in system32 and my 32-bit nasm into syswow64, and it works perfectly :V

**Comment by cheatfreak47** [comment]
I just added the nasm directory to my PATH- but manually defining it does seem like a good idea.

**Comment by GerbilSoft** [comment]
Should be fixed by commit 62afa471c46fd4dd7ea23792dc07bdc7a8b6fab9.
