### ISSUE TITLE
[win32] Loss of transparency in preview pane when loading from cache

### ISSUE THREAD

**Issue by GerbilSoft** [GerbilSoft/rom-properties#82]
<a href="https://github.com/DankRank"><img src="https://avatars2.githubusercontent.com/u/4050457?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [DankRank](https://github.com/DankRank)**
_Friday Jun 16, 2017 at 15:58 GMT_
_Originally opened as https://github.com/GerbilSoft/rom-properties.reworking/issues/82_

----

Occurs on both master (0607b7dd004d7cc4f1cfadc2491f4cbafd3c45eb) and rp-config.KeyManager.win32 (1d588e5e73cfbe081e1fc1431ae41507713a5223)

This is how preview looks like when you click on it for the first time (after clearing cache):
![image](https://user-images.githubusercontent.com/4050457/27234342-5496e60a-52c5-11e7-9662-f31d8fa2cc04.png)

This is how it looks after some clicking around:
![image](https://user-images.githubusercontent.com/4050457/27234361-6686a86e-52c5-11e7-81e6-20a0cfd3f2d3.png)

Windows 10 Version 1607

**Comment by GerbilSoft** [comment]
<a href="https://github.com/DankRank"><img src="https://avatars2.githubusercontent.com/u/4050457?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [DankRank](https://github.com/DankRank)**
_Friday Jun 16, 2017 at 16:13 GMT_

----

Looks like it's a Windows 10 bug, it occurs with PNGs too

**Comment by GerbilSoft** [comment]
<a href="https://github.com/GerbilSoft"><img src="https://avatars2.githubusercontent.com/u/6764716?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [GerbilSoft](https://github.com/GerbilSoft)**
_Saturday Jun 17, 2017 at 16:06 GMT_

----

Can't seem to reproduce this on Windows 7. (Sidenote: Preview pane seems to require either IPreviewHandler or IThumbnailProvider; IThumbnailProvider doesn't work for *.vmi, so no preview shows up for those, even if the *.vms file is present.)

This seems to be a bug with a lot of Windows 10 applications when showing transparent PNGs: https://answers.microsoft.com/en-us/windows/forum/windows_10-start/windows-10-default-photo-viewer-png-files-black/d12d0d36-5f98-4d22-8cc3-79be345975b0

**Comment by GerbilSoft** [comment]
Unfortunately, this appears to be an OS bug and not anything that can be worked around by rom-properties.

It's possible that newer releases of Windows 10 have fixed this. @DankRank can you check this again and see if it still happens?

**Comment by DankRank** [comment]
Still happens
rom-properties 1.5
Windows 1909

**Comment by DankRank** [comment]
The first time after clearing the cache, it always shows up fine. Then for a while the bug happens intermittently. And then it start always showing up without transparency. The background color isn't always black, i.e. the alpha channel is just set to 255 with the RGB left intact.

**Comment by DankRank** [comment]
The image displays normally if the preview pane is at least 5 pixels wider than the minimum width.
![69QBOi9KiF](https://user-images.githubusercontent.com/4050457/85643981-5bd51280-b69e-11ea-90f2-1e70b1c45c86.gif)

**Comment by GerbilSoft** [comment]
This is a Windows bug, so I can't do anything about it.
