### ISSUE TITLE
SJIS conversion failure

### ISSUE THREAD

**Issue by DankRank** [GerbilSoft/rom-properties#83]
Occurs on both master (0607b7dd004d7cc4f1cfadc2491f4cbafd3c45eb) and rp-config.KeyManager.win32 (1d588e5e73cfbe081e1fc1431ae41507713a5223)

Save file: [download](https://www.gamefaqs.com/ps/197341-final-fantasy-vii/saves/16156)

What it displays: ``‚e‚e‚V^‚r‚`‚u‚d‚O‚P^‚Q‚RF‚Q‚O``
What it should display: `ＦＦ７／ＳＡＶＥ０１／２３：２０`

![image](https://user-images.githubusercontent.com/4050457/27234645-6e9a8d26-52c6-11e7-8d0b-e2c0d0c4f2fc.png)

Windows 10 Version 1607

**Comment by GerbilSoft** [comment]
Slightly related: On Linux, no text appears at all due to what appears to be a bug in the cp1252 fallback. I'm specifying //IGNORE, but it seems to abort when it encounters 0x81 anyway.

Adding a Latin-1 fallback on top of that seems to fix it.

**Comment by GerbilSoft** [comment]
Closed by 492e51e4743c27dd486e66351323c350e3fdde3f. (I mentioned #81, not #83, in the commit.)
