### ISSUE TITLE
[win32] Black icon in properties window

### ISSUE THREAD

**Issue by GerbilSoft** [GerbilSoft/rom-properties#84]
<a href="https://github.com/DankRank"><img src="https://avatars2.githubusercontent.com/u/4050457?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [DankRank](https://github.com/DankRank)**
_Friday Jun 16, 2017 at 16:37 GMT_
_Originally opened as https://github.com/GerbilSoft/rom-properties.reworking/issues/84_

----

Occurs on master (0607b7dd004d7cc4f1cfadc2491f4cbafd3c45eb) 

I can't find a reliable way to reproduce this, but this usually happens to the first few files opened after restarting explorer.exe. One time, the first file I opened was ok, but the second had black icon. Maybe it's cache related? Usually fixes itself after a while.

This happened to me on following extensions: *.nds, *.gci, *.psv, *.dci. I shall note that I don't have any of these extensions associated with anything other than rom-properties.

![image](https://user-images.githubusercontent.com/4050457/27235424-7d92776e-52c9-11e7-9ee6-38bc38c939e4.png)

Windows 10 Version 1607

**Comment by GerbilSoft** [comment]
@DankRank Is this issue still occurring?

**Comment by DankRank** [comment]
Can't reproduce on Win 1909, RP 1.6.1

**Comment by GerbilSoft** [comment]
Closing this then.
