### ISSUE TITLE
Slight Change to NDS roms

### ISSUE THREAD

**Issue by cheatfreak47** [GerbilSoft/rom-properties#91]
Instead of 
Secure Area: Mask Rom

you should probably have it say decrypted/encrypted independant of the mask rom being present, and add a new line

Mask Rom: Yes or Mask Rom: No

**Comment by cheatfreak47** [comment]
This is a necessary change btw, as there some SRLs from Wii U VC have both encrypted and decrypted secure areas (odd, I know but it's true)

**Comment by GerbilSoft** [comment]
"Mask ROM" means the $1000-$2FFF area is non-zero. This area is normally unreadable on DS cartridges (or the command to read them isn't known), but it seems to be filled with random data in ROM files built using the official SDK. That's why DSiWare and Wii U SRLs both show up as "Mask ROM".
