### ISSUE TITLE
libpng: pnglibconf.dfa needs to be LF line endings.

### ISSUE THREAD

**Issue by GerbilSoft** [GerbilSoft/rom-properties#95]
`awk` chokes if pnglibconf.dfa has CRLF line endings. We need to set a .gitattributes entry such that pnglibconf.dfa is always checked out as LF regardless of platform.

This bug was reported by @cheatfreak47 on GBAtemp:
https://gbatemp.net/threads/rom-properties-page-shell-extension.442424/page-3#post-7481546

**Comment by GerbilSoft** [comment]
Fixed by commit 8767e15e6c8fde17b2b1126d2dcfd4506f549583.

**Comment by cheatfreak47** [comment]
confirming as fixed, build now works properly without any file modifications.
