### ISSUE TITLE
+x mode is not set on rp-config

### ISSUE THREAD

**Issue by DankRank** [GerbilSoft/rom-properties#96]
@GerbilSoft told me that it's supposed to be a symlink to rp-stub, but when I install it on my kubuntu, it's a separate file with mode 644.

**Comment by GerbilSoft** [comment]
This is normally not noticeable in the packaged version, since `rp-config` is replaced with a symlink in the Debian packaging scripts, but it should be fixed for source builds.

**Comment by GerbilSoft** [comment]
Fixed by commit b51a71e846e9cc8b1d60a9ed2b1a56b125e60758.
